include_guard(GLOBAL)

function(tesseract_task_composer_ensure_cereal_target)
  find_path(CEREAL_INCLUDE_DIR NAMES cereal/cereal.hpp)
  if(NOT CEREAL_INCLUDE_DIR)
    message(FATAL_ERROR "Failed to find cereal headers. Please install libcereal-dev.")
  endif()

  if(TARGET cereal::cereal)
    get_target_property(_cereal_interface_dirs cereal::cereal INTERFACE_INCLUDE_DIRECTORIES)
    set(_cereal_reset_interface FALSE)
    if(NOT _cereal_interface_dirs)
      set(_cereal_reset_interface TRUE)
    else()
      foreach(_cereal_dir IN LISTS _cereal_interface_dirs)
        if("${_cereal_dir}" STREQUAL "/include")
          set(_cereal_reset_interface TRUE)
          break()
        endif()
        if(_cereal_dir MATCHES "\\$<")
          continue()
        endif()
        if(NOT EXISTS "${_cereal_dir}")
          set(_cereal_reset_interface TRUE)
          break()
        endif()
      endforeach()
    endif()

    if(_cereal_reset_interface)
      set_property(TARGET cereal::cereal PROPERTY INTERFACE_INCLUDE_DIRECTORIES "${CEREAL_INCLUDE_DIR}")
    endif()
  else()
    add_library(tesseract_task_composer_cereal INTERFACE)
    target_include_directories(tesseract_task_composer_cereal INTERFACE "${CEREAL_INCLUDE_DIR}")
    add_library(cereal::cereal ALIAS tesseract_task_composer_cereal)
  endif()
endfunction()
