# Generated by Easy Manipulator Improved ROS 2 conversion.

from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument
from launch.substitutions import Command, LaunchConfiguration, PathJoinSubstitution
from launch_ros.actions import Node
from launch_ros.parameter_descriptions import ParameterValue
from launch_ros.substitutions import FindPackageShare
from launch.substitutions import FindExecutable


DESCRIPTION_PACKAGE = "double_fixture"


def generate_launch_description():
    gui = LaunchConfiguration("gui")

    robot_description = ParameterValue(
        Command(
            [
                FindExecutable(name="cat"),
                " ",
                PathJoinSubstitution(
                    [FindPackageShare(DESCRIPTION_PACKAGE), "urdf", "double_fixture.urdf"]
                ),
            ]
        ),
        value_type=str,
    )

    joint_state_publisher = Node(
        package="joint_state_publisher",
        executable="joint_state_publisher",
        output="screen",
        parameters=[{"use_gui": gui}],
    )

    robot_state_publisher = Node(
        package="robot_state_publisher",
        executable="robot_state_publisher",
        output="screen",
        parameters=[{"robot_description": robot_description}],
    )

    rviz = Node(
        package="rviz2",
        executable="rviz2",
        output="screen",
        arguments=[
            "-d",
            PathJoinSubstitution([FindPackageShare(DESCRIPTION_PACKAGE), "urdf.rviz"]),
        ],
    )

    return LaunchDescription(
        [
            DeclareLaunchArgument("model"),
            DeclareLaunchArgument("gui", default_value="false"),
            joint_state_publisher,
            robot_state_publisher,
            rviz,
        ]
    )
