# Autogenerated from ROS 1 launch file.
from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, GroupAction
from launch.actions import IncludeLaunchDescription
from launch.conditions import IfCondition, UnlessCondition
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch.substitutions import Command
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node
from launch_ros.actions import PushRosNamespace
from launch_ros.parameter_descriptions import ParameterValue
import os

def generate_launch_description():
    actions = []
    actions.append(IncludeLaunchDescription(PythonLaunchDescriptionSource(os.path.join(get_package_share_directory('gazebo_ros'), 'launch/empty_world.launch.py'))))
    actions.append(Node(package='tf', executable='static_transform_publisher', name='tf_footprint_base', arguments=['0', '0', '0', '0', '0', '0', 'base_link', 'base_footprint', '40']))
    actions.append(Node(package='gazebo_ros', executable='spawn_model', name='spawn_model', output='screen', arguments=['-file', '$(find', 'double_fixture)/urdf/double_fixture.urdf', '-urdf', '-model', 'double_fixture']))
    actions.append(Node(package='rostopic', executable='rostopic', name='fake_joint_calibration', arguments=['pub', '/calibrated', 'std_msgs/Bool', 'true']))
    return LaunchDescription(actions)
