# Generated by Easy Manipulator Improved ROS 2 conversion.

from launch import LaunchDescription
from launch.actions import ExecuteProcess, IncludeLaunchDescription
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch.substitutions import PathJoinSubstitution
from launch_ros.actions import Node
from launch_ros.substitutions import FindPackageShare


DESCRIPTION_PACKAGE = "double_fixture"


def generate_launch_description():
    gazebo = IncludeLaunchDescription(
        PythonLaunchDescriptionSource(
            PathJoinSubstitution([FindPackageShare("gazebo_ros"), "launch", "gazebo.launch.py"])
        )
    )

    static_tf = Node(
        package="tf2_ros",
        executable="static_transform_publisher",
        arguments=["0", "0", "0", "0", "0", "0", "base_link", "base_footprint"],
    )

    spawn_entity = Node(
        package="gazebo_ros",
        executable="spawn_entity.py",
        output="screen",
        arguments=[
            "-entity",
            "double_fixture",
            "-file",
            PathJoinSubstitution(
                [FindPackageShare(DESCRIPTION_PACKAGE), "urdf", "double_fixture.urdf"]
            ),
        ],
    )

    calibration_pub = ExecuteProcess(
        cmd=[
            "ros2",
            "topic",
            "pub",
            "/calibrated",
            "std_msgs/msg/Bool",
            "{data: true}",
            "-1",
        ],
        output="screen",
    )

    return LaunchDescription([gazebo, static_tf, spawn_entity, calibration_pub])
