# Ensure consumers of tesseract_common can locate the custom CMake modules
# that ship with the package (e.g. FindTinyXML2.cmake).  This mirrors the
# behaviour of the upstream project which appends its module directory to
# CMAKE_MODULE_PATH from its exported package configuration. The module path
# is three levels up from the current list directory (install root) and then
# under lib/cmake/tesseract_common.
set(_tesseract_common_prefix "${CMAKE_CURRENT_LIST_DIR}/../../..")
get_filename_component(_tesseract_common_prefix "${_tesseract_common_prefix}" ABSOLUTE)
set(_tesseract_common_module_dir "${_tesseract_common_prefix}/lib/cmake/tesseract_common")
if(EXISTS "${_tesseract_common_module_dir}")
  if(NOT "${_tesseract_common_module_dir}" IN_LIST CMAKE_MODULE_PATH)
    list(APPEND CMAKE_MODULE_PATH "${_tesseract_common_module_dir}")
  endif()
  if(EXISTS "${_tesseract_common_module_dir}/tesseract_macros.cmake")
    include("${_tesseract_common_module_dir}/tesseract_macros.cmake")
  endif()
endif()

# Older exports of tesseract_common only provide the plain target name or the
# ament-generated "tesseract_common::tesseract_common" target.  Downstream
# packages in this workspace expect to link against the upstream-style
# "tesseract::tesseract_common" target, so recreate that namespace if it is not
# already present.  Re-exporting in this way keeps the interface properties of
# the original imported target intact, regardless of which naming scheme was
# generated by ament.
if(NOT TARGET tesseract::tesseract_common)
  if(TARGET tesseract_common::tesseract_common)
    add_library(tesseract::tesseract_common INTERFACE IMPORTED)
    set_target_properties(tesseract::tesseract_common PROPERTIES
      INTERFACE_LINK_LIBRARIES tesseract_common::tesseract_common)
  elseif(TARGET tesseract_common)
    add_library(tesseract::tesseract_common INTERFACE IMPORTED)
    set_target_properties(tesseract::tesseract_common PROPERTIES
      INTERFACE_LINK_LIBRARIES tesseract_common)
  endif()
endif()

if(NOT TARGET tesseract_common::tesseract_common)
  if(TARGET tesseract::tesseract_common)
    add_library(tesseract_common::tesseract_common INTERFACE IMPORTED)
    set_target_properties(tesseract_common::tesseract_common PROPERTIES
      INTERFACE_LINK_LIBRARIES tesseract::tesseract_common)
  elseif(TARGET tesseract_common)
    add_library(tesseract_common::tesseract_common INTERFACE IMPORTED)
    set_target_properties(tesseract_common::tesseract_common PROPERTIES
      INTERFACE_LINK_LIBRARIES tesseract_common)
  endif()
endif()
unset(_tesseract_common_prefix)
unset(_tesseract_common_module_dir)
