# Ensure consumers of tesseract_common can locate the custom CMake modules
# that ship with the package (e.g. FindTinyXML2.cmake).  This mirrors the
# behaviour of the upstream project which appends its module directory to
# CMAKE_MODULE_PATH from its exported package configuration. The module path
# is three levels up from the current list directory (install root) and then
# under lib/cmake/tesseract_common.
set(_tesseract_common_prefix "${CMAKE_CURRENT_LIST_DIR}/../../..")
get_filename_component(_tesseract_common_prefix "${_tesseract_common_prefix}" ABSOLUTE)
set(_tesseract_common_module_dir "${_tesseract_common_prefix}/lib/cmake/tesseract_common")
if(EXISTS "${_tesseract_common_module_dir}")
  if(NOT "${_tesseract_common_module_dir}" IN_LIST CMAKE_MODULE_PATH)
    list(APPEND CMAKE_MODULE_PATH "${_tesseract_common_module_dir}")
  endif()
  if(EXISTS "${_tesseract_common_module_dir}/tesseract_macros.cmake")
    include("${_tesseract_common_module_dir}/tesseract_macros.cmake")
  endif()
endif()

# Older exports of tesseract_common only provide the plain target name or the
# ament-generated "tesseract_common::tesseract_common" target.  Downstream
# packages in this workspace expect to link against the upstream-style
# "tesseract::tesseract_common" target, so recreate that namespace if it is not
# already present.  Re-exporting in this way keeps the interface properties of
# the original imported target intact, regardless of which naming scheme was
# generated by ament.
set(_tesseract_common_have_exports FALSE)
foreach(_var IN ITEMS LIBRARIES INCLUDE_DIRS COMPILE_DEFINITIONS COMPILE_OPTIONS)
  if(DEFINED tesseract_common_${_var} AND tesseract_common_${_var})
    set(_tesseract_common_have_exports TRUE)
  endif()
endforeach()

if(NOT TARGET tesseract::tesseract_common)
  if(TARGET tesseract_common::tesseract_common)
    add_library(tesseract::tesseract_common INTERFACE IMPORTED GLOBAL)
    set_target_properties(tesseract::tesseract_common PROPERTIES
      INTERFACE_LINK_LIBRARIES tesseract_common::tesseract_common)
  elseif(TARGET tesseract_common)
    add_library(tesseract::tesseract_common INTERFACE IMPORTED GLOBAL)
    set_target_properties(tesseract::tesseract_common PROPERTIES
      INTERFACE_LINK_LIBRARIES tesseract_common)
  elseif(_tesseract_common_have_exports)
    add_library(tesseract::tesseract_common INTERFACE IMPORTED GLOBAL)
    if(DEFINED tesseract_common_LIBRARIES AND tesseract_common_LIBRARIES)
      set_property(TARGET tesseract::tesseract_common PROPERTY
        INTERFACE_LINK_LIBRARIES ${tesseract_common_LIBRARIES})
    endif()
    if(DEFINED tesseract_common_INCLUDE_DIRS AND tesseract_common_INCLUDE_DIRS)
      set_property(TARGET tesseract::tesseract_common PROPERTY
        INTERFACE_INCLUDE_DIRECTORIES ${tesseract_common_INCLUDE_DIRS})
    endif()
    if(DEFINED tesseract_common_COMPILE_DEFINITIONS AND tesseract_common_COMPILE_DEFINITIONS)
      set_property(TARGET tesseract::tesseract_common PROPERTY
        INTERFACE_COMPILE_DEFINITIONS ${tesseract_common_COMPILE_DEFINITIONS})
    endif()
    if(DEFINED tesseract_common_COMPILE_OPTIONS AND tesseract_common_COMPILE_OPTIONS)
      set_property(TARGET tesseract::tesseract_common PROPERTY
        INTERFACE_COMPILE_OPTIONS ${tesseract_common_COMPILE_OPTIONS})
    endif()
  endif()
endif()

if(NOT TARGET tesseract_common::tesseract_common)
  if(TARGET tesseract::tesseract_common)
    add_library(tesseract_common::tesseract_common INTERFACE IMPORTED GLOBAL)
    set_target_properties(tesseract_common::tesseract_common PROPERTIES
      INTERFACE_LINK_LIBRARIES tesseract::tesseract_common)
  elseif(TARGET tesseract_common)
    add_library(tesseract_common::tesseract_common INTERFACE IMPORTED GLOBAL)
    set_target_properties(tesseract_common::tesseract_common PROPERTIES
      INTERFACE_LINK_LIBRARIES tesseract_common)
  elseif(_tesseract_common_have_exports)
    add_library(tesseract_common::tesseract_common INTERFACE IMPORTED GLOBAL)
    if(DEFINED tesseract_common_LIBRARIES AND tesseract_common_LIBRARIES)
      set_property(TARGET tesseract_common::tesseract_common PROPERTY
        INTERFACE_LINK_LIBRARIES ${tesseract_common_LIBRARIES})
    endif()
    if(DEFINED tesseract_common_INCLUDE_DIRS AND tesseract_common_INCLUDE_DIRS)
      set_property(TARGET tesseract_common::tesseract_common PROPERTY
        INTERFACE_INCLUDE_DIRECTORIES ${tesseract_common_INCLUDE_DIRS})
    endif()
    if(DEFINED tesseract_common_COMPILE_DEFINITIONS AND tesseract_common_COMPILE_DEFINITIONS)
      set_property(TARGET tesseract_common::tesseract_common PROPERTY
        INTERFACE_COMPILE_DEFINITIONS ${tesseract_common_COMPILE_DEFINITIONS})
    endif()
    if(DEFINED tesseract_common_COMPILE_OPTIONS AND tesseract_common_COMPILE_OPTIONS)
      set_property(TARGET tesseract_common::tesseract_common PROPERTY
        INTERFACE_COMPILE_OPTIONS ${tesseract_common_COMPILE_OPTIONS})
    endif()
  endif()
endif()
unset(_tesseract_common_prefix)
unset(_tesseract_common_module_dir)
unset(_tesseract_common_have_exports)
