# Provide a fallback implementation of the find_bullet() helper that mimics
# the upstream ros_industrial_cmake_boilerplate behavior. This is required at
# both build time (when configuring the tesseract_collision package itself)
# and at install-time when downstream packages include the exported
# tesseract_collision_bulletConfig.cmake file.

if(NOT COMMAND find_bullet)
  function(_tesseract_bullet_get_target_install_prefix target out_var)
    set(_location "")

    get_target_property(_location "${target}" IMPORTED_LOCATION)
    if(NOT _location)
      get_target_property(_imported_configs "${target}" IMPORTED_CONFIGURATIONS)
      foreach(_config IN LISTS _imported_configs)
        if(_location)
          break()
        endif()
        string(TOUPPER "${_config}" _config_upper)
        get_target_property(_candidate "${target}" "IMPORTED_LOCATION_${_config_upper}")
        if(NOT _candidate)
          get_target_property(_candidate "${target}" "IMPORTED_IMPLIB_${_config_upper}")
        endif()
        if(_candidate)
          set(_location "${_candidate}")
        endif()
      endforeach()
    endif()

    if(NOT _location)
      set(${out_var} "" PARENT_SCOPE)
      return()
    endif()

    list(GET _location 0 _resolved_location)
    if(NOT IS_ABSOLUTE "${_resolved_location}")
      get_filename_component(_resolved_location "${_resolved_location}" ABSOLUTE)
    endif()

    get_filename_component(_lib_dir "${_resolved_location}" DIRECTORY)
    set(_search_dir "${_lib_dir}")
    set(_previous "")
    while(NOT _search_dir STREQUAL _previous)
      if(IS_DIRECTORY "${_search_dir}/include")
        set(${out_var} "${_search_dir}" PARENT_SCOPE)
        return()
      endif()
      set(_previous "${_search_dir}")
      get_filename_component(_search_dir "${_search_dir}/.." ABSOLUTE)
    endwhile()

    set(${out_var} "${_lib_dir}" PARENT_SCOPE)
  endfunction()

  function(_tesseract_bullet_find_prefix_from_libraries out_var)
    set(_libs "${ARGN}")
    foreach(_lib IN LISTS _libs)
      if(_lib STREQUAL "debug" OR _lib STREQUAL "optimized" OR _lib STREQUAL "general")
        continue()
      endif()
      if(IS_ABSOLUTE "${_lib}" AND EXISTS "${_lib}")
        get_filename_component(_lib_dir "${_lib}" DIRECTORY)
        set(_search_dir "${_lib_dir}")
        set(_previous "")
        while(NOT _search_dir STREQUAL _previous)
          if(IS_DIRECTORY "${_search_dir}/include")
            set(${out_var} "${_search_dir}" PARENT_SCOPE)
            return()
          endif()
          set(_previous "${_search_dir}")
          get_filename_component(_search_dir "${_search_dir}/.." ABSOLUTE)
        endwhile()
        set(${out_var} "${_lib_dir}" PARENT_SCOPE)
        return()
      endif()
    endforeach()
    set(${out_var} "" PARENT_SCOPE)
  endfunction()

  function(_tesseract_bullet_normalize_includes out_var base_dir)
    set(_base_dir "${base_dir}")
    set(_normalized)
    foreach(_entry IN LISTS ARGN)
      if(_entry MATCHES "^\$<")
        list(APPEND _normalized "${_entry}")
      elseif(IS_ABSOLUTE "${_entry}")
        list(APPEND _normalized "${_entry}")
      elseif(_base_dir)
        get_filename_component(_abs "${_base_dir}/${_entry}" ABSOLUTE)
        list(APPEND _normalized "${_abs}")
      else()
        get_filename_component(_abs "${_entry}" ABSOLUTE)
        list(APPEND _normalized "${_abs}")
      endif()
    endforeach()
    if(_normalized)
      list(REMOVE_DUPLICATES _normalized)
    endif()
    set(${out_var} "${_normalized}" PARENT_SCOPE)
  endfunction()

  function(find_bullet)
    set(HACD_LIBRARY "")

    # Prefer the imported target exported by bullet's CONFIG package if it
    # is available (Ubuntu 22.04+).
    find_package(Bullet CONFIG QUIET)

    if(Bullet_FOUND)
      if(NOT TARGET Bullet3::Bullet)
        if(TARGET Bullet::Bullet)
          add_library(Bullet3::Bullet INTERFACE IMPORTED)
          set_target_properties(Bullet3::Bullet PROPERTIES INTERFACE_LINK_LIBRARIES Bullet::Bullet)

          get_target_property(_bullet_inc Bullet::Bullet INTERFACE_INCLUDE_DIRECTORIES)
          if(_bullet_inc)
            _tesseract_bullet_get_target_install_prefix(Bullet::Bullet _bullet_prefix)
            _tesseract_bullet_normalize_includes(_normalized_inc "${_bullet_prefix}" ${_bullet_inc})
            if(_normalized_inc)
              set_target_properties(Bullet3::Bullet PROPERTIES INTERFACE_INCLUDE_DIRECTORIES "${_normalized_inc}")
            endif()
          endif()
        else()
          # Some distributions export individual bullet component targets
          # instead of the umbrella Bullet::Bullet library.
          set(_bullet_targets)
          foreach(component BulletDynamics BulletCollision LinearMath)
            if(TARGET Bullet::${component})
              list(APPEND _bullet_targets Bullet::${component})
            elseif(TARGET Bullet::${component}_Static)
              list(APPEND _bullet_targets Bullet::${component}_Static)
            endif()
          endforeach()

          if(_bullet_targets)
            add_library(Bullet3::Bullet INTERFACE IMPORTED)
            set_target_properties(Bullet3::Bullet PROPERTIES INTERFACE_LINK_LIBRARIES "${_bullet_targets}")

            set(_include_dirs)
            foreach(tgt IN LISTS _bullet_targets)
              get_target_property(_inc "${tgt}" INTERFACE_INCLUDE_DIRECTORIES)
              if(_inc)
                _tesseract_bullet_get_target_install_prefix("${tgt}" _component_prefix)
                _tesseract_bullet_normalize_includes(_component_includes "${_component_prefix}" ${_inc})
                if(_component_includes)
                  list(APPEND _include_dirs "${_component_includes}")
                endif()
              endif()
            endforeach()

            if(_include_dirs)
              list(REMOVE_DUPLICATES _include_dirs)
              set_target_properties(Bullet3::Bullet PROPERTIES INTERFACE_INCLUDE_DIRECTORIES "${_include_dirs}")
            endif()
          endif()
        endif()
      endif()
    endif()

    if(NOT TARGET Bullet3::Bullet)
      # Fall back to the traditional FindBullet module. This is the path
      # taken on older Ubuntu releases where Bullet does not ship a config
      # file. We create an imported target that mimics the modern
      # Bullet3::Bullet interface expected by downstream code.
      find_package(Bullet REQUIRED)

      if(BULLET_LIBRARIES)
        message(STATUS "FindBullet module located libraries: ${BULLET_LIBRARIES}")
        message(STATUS "FindBullet module library dirs: ${BULLET_LIBRARY_DIRS}")
        message(STATUS "FindBullet module root dir: ${BULLET_ROOT_DIR}")
        set(_search_dirs)
        if(BULLET_LIBRARY_DIRS)
          foreach(_dir IN LISTS BULLET_LIBRARY_DIRS)
            if(IS_ABSOLUTE "${_dir}")
              list(APPEND _search_dirs "${_dir}")
            elseif(BULLET_ROOT_DIR)
              get_filename_component(_abs_dir "${BULLET_ROOT_DIR}/${_dir}" ABSOLUTE)
              list(APPEND _search_dirs "${_abs_dir}")
            else()
              get_filename_component(_abs_dir "${_dir}" ABSOLUTE)
              list(APPEND _search_dirs "${_abs_dir}")
            endif()
          endforeach()
        endif()

        set(_filtered_bullet_libs)
        set(_pending_keyword "")
        foreach(_entry IN LISTS BULLET_LIBRARIES)
          if(_entry STREQUAL "debug" OR _entry STREQUAL "optimized" OR _entry STREQUAL "general")
            set(_pending_keyword "${_entry}")
            continue()
          endif()

          set(_resolved "")
          if(IS_ABSOLUTE "${_entry}" AND EXISTS "${_entry}")
            set(_resolved "${_entry}")
          else()
            if(_search_dirs)
              foreach(_dir IN LISTS _search_dirs)
                foreach(_prefix IN LISTS CMAKE_FIND_LIBRARY_PREFIXES)
                  foreach(_suffix IN LISTS CMAKE_FIND_LIBRARY_SUFFIXES)
                    set(_candidate "${_dir}/${_prefix}${_entry}${_suffix}")
                    if(EXISTS "${_candidate}")
                      set(_resolved "${_candidate}")
                      break()
                    endif()
                  endforeach()
                  if(_resolved)
                    break()
                  endif()
                endforeach()
                if(_resolved)
                  break()
                endif()
              endforeach()
            endif()
            if(NOT _resolved)
              find_library(_resolved NAMES ${_entry})
            endif()
          endif()

          if(_resolved)
            if(_pending_keyword)
              list(APPEND _filtered_bullet_libs "${_pending_keyword}")
              set(_pending_keyword "")
            endif()
            list(APPEND _filtered_bullet_libs "${_resolved}")
          else()
            if(_pending_keyword)
              message(WARNING "Bullet library keyword ${_pending_keyword} ignored because ${_entry} was not found")
              set(_pending_keyword "")
            endif()
            if(_entry STREQUAL "BulletInverseDynamics")
              message(STATUS "Bullet library ${_entry} is not available; continuing without inverse dynamics support")
            else()
              message(WARNING "Bullet library ${_entry} listed by FindBullet but was not found on this system; omitting it from Bullet3::Bullet")
            endif()
          endif()
        endforeach()

        if(_pending_keyword)
          message(WARNING "Trailing Bullet library keyword ${_pending_keyword} ignored because it did not precede a library entry")
        endif()

        if(_filtered_bullet_libs)
          # On some older Bullet releases the FindBullet module omits the
          # LinearMath component even though it is required for
          # btConvexHullComputer symbols that we use in
          # convex_hull_utils.cpp and the create_convex_hull utility. Make
          # sure it is explicitly appended when missing so downstream link
          # steps do not fail with undefined references.
          set(_linear_math_present OFF)
          foreach(_entry IN LISTS _filtered_bullet_libs)
            if(_entry STREQUAL "debug" OR _entry STREQUAL "optimized" OR _entry STREQUAL "general")
              continue()
            endif()
            get_filename_component(_lib_name "${_entry}" NAME_WE)
            if(_lib_name MATCHES "LinearMath")
              set(_linear_math_present ON)
              break()
            endif()
          endforeach()

          if(NOT _linear_math_present)
            set(_linear_math_lib "")
            if(_search_dirs)
              find_library(_linear_math_lib NAMES LinearMath HINTS ${_search_dirs})
            endif()
            if(NOT _linear_math_lib)
              find_library(_linear_math_lib NAMES LinearMath)
            endif()
            if(_linear_math_lib)
              list(APPEND _filtered_bullet_libs "${_linear_math_lib}")
            else()
              message(WARNING "FindBullet.cmake did not report a LinearMath library and it could not be located automatically; the resulting Bullet3::Bullet target may be missing btConvexHullComputer symbols")
            endif()
          endif()

          add_library(Bullet3::Bullet INTERFACE IMPORTED)
          _tesseract_bullet_find_prefix_from_libraries(_bullet_prefix ${_filtered_bullet_libs})
          _tesseract_bullet_normalize_includes(_bullet_includes "${_bullet_prefix}" ${BULLET_INCLUDE_DIRS})
          set_target_properties(Bullet3::Bullet PROPERTIES
                                INTERFACE_INCLUDE_DIRECTORIES "${_bullet_includes}"
                                INTERFACE_LINK_LIBRARIES "${_filtered_bullet_libs}")
        else()
          message(FATAL_ERROR "FindBullet.cmake did not yield any usable Bullet libraries")
        endif()
      else()
        message(FATAL_ERROR "Failed to locate Bullet libraries while configuring tesseract_collision")
      endif()
    endif()

    # Try to locate the HACD convex decomposition library. It is optional,
    # so populate the variable only when a library is discovered.
    find_library(_hacd_library NAMES HACD hacd)
    if(_hacd_library)
      set(HACD_LIBRARY "${_hacd_library}" PARENT_SCOPE)
    else()
      set(HACD_LIBRARY "" PARENT_SCOPE)
    endif()
  endfunction()
endif()
