from __future__ import annotations

import json
import shutil
import subprocess
import sys
from pathlib import Path


def test_workcell_builder_preview_bundle_created(tmp_path: Path) -> None:
    scene_src = Path("scenes/ur5_2f_builder_pick_place_demo")
    scene = tmp_path / "scene"
    shutil.copytree(scene_src, scene)

    out = tmp_path / "studio_out"
    run = subprocess.run([
        sys.executable,
        "scripts/workcell_studio.py",
        "import-builder-scene",
        "--scene-package",
        str(scene),
        "--output-dir",
        str(out),
        "--validate",
        "--project-name",
        "preview_bundle_demo",
    ], capture_output=True, text=True, check=False)
    assert run.returncode == 0, run.stdout + run.stderr

    summary = json.loads((out / "workcell_studio_import_summary.json").read_text(encoding="utf-8"))
    bundle = Path(summary["preview_bundle_dir"])
    assert bundle.exists()

    expected = {
        "builder_export_summary.json",
        "environment_preview.svg",
        "environment_preview.html",
        "readiness_summary.md",
        "readiness_summary.html",
        "generated_launch_commands.md",
    }
    assert expected.issubset({p.name for p in bundle.iterdir()})

    export_summary = json.loads((bundle / "builder_export_summary.json").read_text(encoding="utf-8"))
    blob = json.dumps(export_summary)
    assert "robot" in blob
    assert "task" in blob
    assert "fake" in json.dumps(summary).lower()

    readiness = (bundle / "readiness_summary.md").read_text(encoding="utf-8")
    assert "Final readiness:" in readiness
    assert "No-motion safety statement" in readiness

    launch_cmds = (bundle / "generated_launch_commands.md").read_text(encoding="utf-8")
    assert "Fake hardware" in launch_cmds
    assert "Real hardware" in launch_cmds
    assert "Not generated by default" in launch_cmds
