from __future__ import annotations
import subprocess, tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]

def test_studio_pack_has_readiness_and_no_real_hw_default() -> None:
    with tempfile.TemporaryDirectory() as d:
        scene=Path(d)/'scene'; scene.mkdir()
        (scene/'environment.yaml').write_text('robot: {name: generic_cartesian}\nend_effector: {name: suction}\nobjects: {}\n')
        (scene/'workcell_builder_metadata.yaml').write_text('{"robot":{"preview_only":true}}')
        out=Path(d)/'out'
        subprocess.run(['python3', str(REPO_ROOT/'scripts/workcell_studio.py'), 'import-builder-scene', '--scene-package', str(scene), '--output-dir', str(out), '--project-name', 'demo', '--generate-readiness-pack'], check=True)
        bundle=out/'studio_pack'
        launch=(bundle/'generated_launch_commands.md').read_text()
        readiness=(bundle/'readiness_summary.md').read_text()
        assert 'Real hardware' in launch and 'Not generated by default' in launch
        assert 'No-motion safety statement' in readiness
