# Generated by Easy Manipulator Improved ROS 2 conversion.

from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, IncludeLaunchDescription
from launch.conditions import IfCondition
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch.substitutions import LaunchConfiguration, PathJoinSubstitution
from launch_ros.actions import Node
from launch_ros.substitutions import FindPackageShare


def generate_launch_description():
    reset = LaunchConfiguration("reset")
    database_path = LaunchConfiguration("moveit_warehouse_database_path")

    return LaunchDescription(
        [
            DeclareLaunchArgument("reset", default_value="false"),
            DeclareLaunchArgument(
                "moveit_warehouse_database_path",
                default_value=PathJoinSubstitution(
                    [FindPackageShare("ur3_moveit_config"), "default_warehouse_mongo_db"]
                ),
            ),
            IncludeLaunchDescription(
                PythonLaunchDescriptionSource(
                    PathJoinSubstitution(
                        [FindPackageShare("ur3_moveit_config"), "launch", "warehouse.launch.py"]
                    )
                ),
                launch_arguments={"moveit_warehouse_database_path": database_path}.items(),
            ),
            Node(
                package="moveit_ros_warehouse",
                executable="moveit_init_demo_warehouse",
                output="screen",
                condition=IfCondition(reset),
            ),
        ]
    )
