robot:
  name: ur5
  brand: universal_robot
  filepath: ""
  base_link: base_link
  ee_link: tool0
  links:
    - base_link
    - shoulder_link
    - upper_arm_link
    - forearm_link
    - wrist_1_link
    - wrist_2_link
    - wrist_3_link
    - ee_link
    - base
    - tool0
end_effector:
  name: robotiq_3f
  brand: robotiq_3f_gripper
  filepath: /home/rosi5/emd_ws/src/assets/end_effectors/robotiq_3f_gripper/robotiq_3f_gripper_description
  base_link: palm
  robot_link: tool0
  ee_type: finger
  attributes:
    fingers: 2
  origin:
    x: 0
    y: 0
    z: 0
    roll: 0
    pitch: -1.5707
    yaw: 0
  links:
    - palm
    - finger_1_link_0
    - finger_1_link_1
    - finger_1_link_2
    - finger_1_link_3
    - finger_2_link_0
    - finger_2_link_1
    - finger_2_link_2
    - finger_2_link_3
    - finger_middle_link_0
    - finger_middle_link_1
    - finger_middle_link_2
    - finger_middle_link_3
objects:
  table:
    child_link: table
    links:
      table:
        visual:
          name: table
          geometry:
            filepath: package://table_description/meshes/visual/table.stl
            scale:
              scale_x: 0.001
              scale_y: 0.001
              scale_z: 0.001
        collision:
          name: None
          geometry:
            filepath: package://table_description/meshes/visual/table.stl
            scale:
              scale_x: 0.001
              scale_y: 0.001
              scale_z: 0.001
    table_base_joint:
      ext_joint_type: fixed
      child_link: table
external joints:
  table:
    parent object: world
    parent link: world
