# Generated by Easy Manipulator Improved ROS 2 conversion.

from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument
from launch.conditions import IfCondition, UnlessCondition
from launch.substitutions import Command, LaunchConfiguration, PathJoinSubstitution
from launch_ros.actions import Node
from launch_ros.parameter_descriptions import ParameterValue
from launch_ros.substitutions import FindPackageShare
from launch.substitutions import FindExecutable


MOVEIT_CONFIG_PACKAGE = "ur10_moveit_config"
DESCRIPTION_PACKAGE = "ur_description"
ROBOT_NAME = "ur10"
URDF_FILE = "ur_macro.xacro"
SRDF_FILE = "ur10.srdf"


def generate_robot_description(limited_value):
    return ParameterValue(
        Command(
            [
                FindExecutable(name="xacro"),
                " ",
                PathJoinSubstitution(
                    [FindPackageShare(DESCRIPTION_PACKAGE), "urdf", URDF_FILE]
                ),
                " ",
                "ur_type:=",
                ROBOT_NAME,
                " ",
                "name:=",
                ROBOT_NAME,
                " ",
                "safety_limits:=",
                limited_value,
            ]
        ),
        value_type=str,
    )


def generate_robot_description_semantic():
    return ParameterValue(
        Command(
            [
                FindExecutable(name="cat"),
                " ",
                PathJoinSubstitution(
                    [FindPackageShare(MOVEIT_CONFIG_PACKAGE), "config", SRDF_FILE]
                ),
            ]
        ),
        value_type=str,
    )


def generate_launch_description():
    limited = LaunchConfiguration("limited")
    load_robot_description = LaunchConfiguration("load_robot_description")

    robot_description = generate_robot_description(limited)
    robot_description_semantic = generate_robot_description_semantic()

    kinematics_yaml = PathJoinSubstitution(
        [FindPackageShare(MOVEIT_CONFIG_PACKAGE), "config", "kinematics.yaml"]
    )
    joint_limits_yaml = PathJoinSubstitution(
        [FindPackageShare(MOVEIT_CONFIG_PACKAGE), "config", "joint_limits.yaml"]
    )

    robot_state_publisher = Node(
        package="robot_state_publisher",
        executable="robot_state_publisher",
        output="screen",
        condition=IfCondition(load_robot_description),
        parameters=[
            {
                "robot_description": robot_description,
                "robot_description_semantic": robot_description_semantic,
            },
            kinematics_yaml,
            joint_limits_yaml,
        ],
    )

    return LaunchDescription(
        [
            DeclareLaunchArgument("limited", default_value="false"),
            DeclareLaunchArgument("load_robot_description", default_value="true"),
            robot_state_publisher,
        ]
    )
