# Autogenerated from ROS 1 launch file.
from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, GroupAction
from launch.actions import IncludeLaunchDescription
from launch.conditions import IfCondition, UnlessCondition
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch.substitutions import Command
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node
from launch_ros.actions import PushRosNamespace
from launch_ros.parameter_descriptions import ParameterValue
import os

def generate_launch_description():
    actions = []
    actions.append(DeclareLaunchArgument('gui', default_value='True'))
    actions.append(IncludeLaunchDescription(PythonLaunchDescriptionSource(os.path.join(get_package_share_directory('robotiq_85_description'), 'launch/upload_robotiq_85_gripper.launch.py'))))
    actions.append(Node(package='rclcpp_components', executable='component_container', name='parameter_loader_1', parameters=[{'use_gui': LaunchConfiguration('gui')}]))
    actions.append(Node(package='joint_state_publisher', executable='joint_state_publisher', name='joint_state_publisher'))
    actions.append(Node(package='robot_state_publisher', executable='state_publisher', name='robot_state_publisher'))
    actions.append(Node(package='rviz', executable='rviz', name='rviz', arguments=['-d', '$(find', 'robotiq_85_description)/urdf.rviz']))
    return LaunchDescription(actions)
