# Generated by Easy Manipulator Improved ROS 2 conversion.

from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, IncludeLaunchDescription
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch.substitutions import LaunchConfiguration, PathJoinSubstitution
from launch_ros.actions import Node
from launch_ros.substitutions import FindPackageShare


DESCRIPTION_PACKAGE = "robotiq_85_description"


def generate_launch_description():
    gui = LaunchConfiguration("gui")

    upload = IncludeLaunchDescription(
        PythonLaunchDescriptionSource(
            PathJoinSubstitution(
                [FindPackageShare(DESCRIPTION_PACKAGE), "launch", "upload_robotiq_85_gripper.launch.py"]
            )
        )
    )

    joint_state_publisher = Node(
        package="joint_state_publisher",
        executable="joint_state_publisher",
        output="screen",
        parameters=[{"use_gui": gui}],
    )

    robot_state_publisher = Node(
        package="robot_state_publisher",
        executable="robot_state_publisher",
        output="screen",
    )

    rviz = Node(
        package="rviz2",
        executable="rviz2",
        output="screen",
        arguments=[
            "-d",
            PathJoinSubstitution([FindPackageShare(DESCRIPTION_PACKAGE), "urdf.rviz"]),
        ],
    )

    return LaunchDescription(
        [
            DeclareLaunchArgument("gui", default_value="true"),
            upload,
            joint_state_publisher,
            robot_state_publisher,
            rviz,
        ]
    )
