# Generated by Easy Manipulator Improved ROS 2 conversion.

from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument
from launch.conditions import IfCondition, UnlessCondition
from launch.substitutions import Command, LaunchConfiguration, PathJoinSubstitution
from launch_ros.actions import SetParameter
from launch_ros.parameter_descriptions import ParameterValue
from launch_ros.substitutions import FindPackageShare
from launch.substitutions import FindExecutable


DESCRIPTION_PACKAGE = "robotiq_85_description"


def generate_launch_description():
    kinova_coupler = LaunchConfiguration("kinova_coupler")

    robot_description = ParameterValue(
        Command(
            [
                FindExecutable(name="xacro"),
                " ",
                PathJoinSubstitution(
                    [
                        FindPackageShare(DESCRIPTION_PACKAGE),
                        "urdf",
                        "robotiq_85_gripper.xacro",
                    ]
                ),
            ]
        ),
        value_type=str,
    )

    robot_description_coupled = ParameterValue(
        Command(
            [
                FindExecutable(name="xacro"),
                " ",
                PathJoinSubstitution(
                    [
                        FindPackageShare(DESCRIPTION_PACKAGE),
                        "urdf",
                        "kinova_robotiq_85_gripper.xacro",
                    ]
                ),
            ]
        ),
        value_type=str,
    )

    return LaunchDescription(
        [
            DeclareLaunchArgument("kinova_coupler", default_value="true"),
            SetParameter(
                name="robot_description",
                value=robot_description,
                condition=UnlessCondition(kinova_coupler),
            ),
            SetParameter(
                name="robot_description",
                value=robot_description_coupled,
                condition=IfCondition(kinova_coupler),
            ),
        ]
    )
