# Autogenerated from ROS 1 launch file.
from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, GroupAction
from launch.actions import IncludeLaunchDescription
from launch.conditions import IfCondition, UnlessCondition
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch.substitutions import Command
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node
from launch_ros.actions import PushRosNamespace
from launch_ros.parameter_descriptions import ParameterValue
import os

def generate_launch_description():
    actions = []
    actions.append(DeclareLaunchArgument('kinova_coupler', default_value='true'))
    actions.append(Node(package='rclcpp_components', executable='component_container', name='parameter_loader_1', parameters=[{'robot_description': ParameterValue(Command(['xacro', '--inorder', os.path.join(get_package_share_directory('robotiq_85_description'), 'urdf/robotiq_85_gripper.xacro')]), value_type=str)}], condition=UnlessCondition(LaunchConfiguration('kinova_coupler'))))
    actions.append(Node(package='rclcpp_components', executable='component_container', name='parameter_loader_2', parameters=[{'robot_description': ParameterValue(Command(['xacro', '--inorder', os.path.join(get_package_share_directory('robotiq_85_description'), 'urdf/kinova_robotiq_85_gripper.xacro')]), value_type=str)}], condition=IfCondition(LaunchConfiguration('kinova_coupler'))))
    return LaunchDescription(actions)
