# Generated by Easy Manipulator Improved ROS 2 conversion.

from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument
from launch.conditions import IfCondition, UnlessCondition
from launch.substitutions import Command, LaunchConfiguration, PathJoinSubstitution, PythonExpression
from launch_ros.actions import Node
from launch_ros.parameter_descriptions import ParameterValue
from launch_ros.substitutions import FindPackageShare
from launch.substitutions import FindExecutable


MOVEIT_CONFIG_PACKAGE = "panda_moveit_config"
DESCRIPTION_PACKAGE = "moveit_resources_panda_description"
URDF_FILE = "panda.urdf"


def generate_robot_description():
    return ParameterValue(
        Command(
            [
                FindExecutable(name="cat"),
                " ",
                PathJoinSubstitution(
                    [FindPackageShare(DESCRIPTION_PACKAGE), "urdf", URDF_FILE]
                ),
            ]
        ),
        value_type=str,
    )


def generate_robot_description_semantic(load_gripper_value):
    srdf_file = PathJoinSubstitution(
        [
            FindPackageShare(MOVEIT_CONFIG_PACKAGE),
            "config",
            PythonExpression(
                [
                    "'panda_arm_hand.srdf.xacro' if ",
                    load_gripper_value,
                    " == 'true' else 'panda_arm.srdf.xacro'",
                ]
            ),
        ]
    )
    return ParameterValue(
        Command([FindExecutable(name="xacro"), " ", srdf_file]),
        value_type=str,
    )


def generate_launch_description():
    load_gripper = LaunchConfiguration("load_gripper")
    rviz_tutorial = LaunchConfiguration("rviz_tutorial")

    robot_description = generate_robot_description()
    robot_description_semantic = generate_robot_description_semantic(load_gripper)

    kinematics_yaml = PathJoinSubstitution(
        [FindPackageShare(MOVEIT_CONFIG_PACKAGE), "config", "kinematics.yaml"]
    )
    joint_limits_yaml = PathJoinSubstitution(
        [FindPackageShare(MOVEIT_CONFIG_PACKAGE), "config", "joint_limits.yaml"]
    )

    rviz_config = PathJoinSubstitution(
        [
            FindPackageShare(MOVEIT_CONFIG_PACKAGE),
            "launch",
            PythonExpression(
                [
                    "'moveit_empty.rviz' if ",
                    rviz_tutorial,
                    " == 'true' else 'moveit.rviz'",
                ]
            ),
        ]
    )

    rviz = Node(
        package="rviz2",
        executable="rviz2",
        output="screen",
        arguments=["-d", rviz_config],
        parameters=[
            {
                "robot_description": robot_description,
                "robot_description_semantic": robot_description_semantic,
            },
            kinematics_yaml,
            joint_limits_yaml,
        ],
    )

    return LaunchDescription(
        [
            DeclareLaunchArgument("load_gripper", default_value="true"),
            DeclareLaunchArgument("rviz_tutorial", default_value="false"),
            rviz,
        ]
    )
