# Generated by Easy Manipulator Improved ROS 2 conversion.


from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument
from launch.conditions import IfCondition, UnlessCondition
from launch.substitutions import LaunchConfiguration, PathJoinSubstitution
from launch_ros.actions import Node
from launch_ros.substitutions import FindPackageShare
from moveit_configs_utils import MoveItConfigsBuilder


PACKAGE_NAME = "panda_moveit_config"
ROBOT_NAME = "panda"
DESCRIPTION_PACKAGE = "panda_description"
URDF_PATH = ['urdf', 'panda.urdf']
SRDF_PATH = ['config', 'panda_arm_hand.srdf.xacro']
URDF_MAPPINGS = {}


def build_moveit_config():
    return (
        MoveItConfigsBuilder(ROBOT_NAME, package_name=PACKAGE_NAME)
        .robot_description(
            file_path=PathJoinSubstitution([FindPackageShare(DESCRIPTION_PACKAGE), *URDF_PATH]),
            mappings=URDF_MAPPINGS,
        )
        .robot_description_semantic(
            file_path=PathJoinSubstitution([FindPackageShare(PACKAGE_NAME), *SRDF_PATH])
        )
        .robot_description_kinematics(
            file_path=PathJoinSubstitution([FindPackageShare(PACKAGE_NAME), "config", "kinematics.yaml"])
        )
        .robot_description_planning(
            file_path=PathJoinSubstitution([FindPackageShare(PACKAGE_NAME), "config", "joint_limits.yaml"])
        )
        .to_moveit_configs()
    )


def generate_launch_description():
    moveit_config = build_moveit_config()

    move_group = Node(
        package="moveit_ros_move_group",
        executable="move_group",
        output="screen",
        parameters=[moveit_config.to_dict()],
    )

    return LaunchDescription([move_group])
