# Generated by Easy Manipulator Improved ROS 2 conversion.

import os
from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, IncludeLaunchDescription
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch.substitutions import LaunchConfiguration, PathJoinSubstitution, PythonExpression
from launch_ros.actions import Node

PACKAGE_NAME = "panda_moveit_config"


def generate_launch_description():
    package_share = get_package_share_directory(PACKAGE_NAME)
    launch_actions = []

    launch_actions.append(
        IncludeLaunchDescription(
            PythonLaunchDescriptionSource(
                PathJoinSubstitution([package_share, "launch", "ompl_planning_pipeline.launch.py"])
            ),
            launch_arguments=[("planning_adapters", 'default_planner_request_adapters/AddTimeParameterization        default_planner_request_adapters/FixWorkspaceBounds        default_planner_request_adapters/FixStartStateBounds        default_planner_request_adapters/FixStartStateCollision        default_planner_request_adapters/FixStartStatePathConstraints        chomp/OptimizerAdapter')],
        )
    )

    parameters = []
    parameters.append(
        {
            "trajectory_initialization_method": 'fillTrajectory',
        }
    )
    parameters.append(os.path.join(package_share, 'config', 'chomp_planning.yaml'))

    launch_actions.append(
        Node(
            package="moveit_ros_move_group",
            executable="move_group",
            output="screen",
            parameters=parameters,
        )
    )

    return LaunchDescription(launch_actions)
