# Generated by Easy Manipulator Improved ROS 2 conversion.

from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, IncludeLaunchDescription
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch.substitutions import LaunchConfiguration, PathJoinSubstitution
from launch_ros.actions import Node
from launch_ros.substitutions import FindPackageShare


MOVEIT_CONFIG_PACKAGE = "panda_moveit_config"


def generate_launch_description():
    load_gripper = LaunchConfiguration("load_gripper")

    controller_spawner = Node(
        package="controller_manager",
        executable="spawner",
        output="screen",
        arguments=["position_joint_trajectory_controller"],
    )

    move_group = IncludeLaunchDescription(
        PythonLaunchDescriptionSource(
            PathJoinSubstitution(
                [FindPackageShare(MOVEIT_CONFIG_PACKAGE), "launch", "move_group.launch.py"]
            )
        ),
        launch_arguments={"load_gripper": load_gripper}.items(),
    )

    return LaunchDescription(
        [
            DeclareLaunchArgument("load_gripper", default_value="true"),
            controller_spawner,
            move_group,
        ]
    )
