# Autogenerated from ROS 1 launch file.
from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, GroupAction
from launch.actions import IncludeLaunchDescription
from launch.conditions import IfCondition, UnlessCondition
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch.substitutions import Command
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node
from launch_ros.actions import PushRosNamespace
from launch_ros.parameter_descriptions import ParameterValue
import os

def generate_launch_description():
    actions = []
    actions.append(DeclareLaunchArgument('load_gripper', default_value='true'))
    actions.append(Node(package='controller_manager', executable='spawner', name='controller_spawner', output='screen', arguments=['position_joint_trajectory_controller'], respawn=False))
    actions.append(IncludeLaunchDescription(PythonLaunchDescriptionSource(os.path.join(get_package_share_directory('moveit_resources_panda_moveit_config'), 'launch/move_group.launch.py')), launch_arguments=dict([('load_gripper', LaunchConfiguration('load_gripper'))]).items()))
    return LaunchDescription(actions)
