# Autogenerated from ROS 1 launch file.
from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, GroupAction
from launch.actions import IncludeLaunchDescription
from launch.conditions import IfCondition, UnlessCondition
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch.substitutions import Command
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node
from launch_ros.actions import PushRosNamespace
from launch_ros.parameter_descriptions import ParameterValue
import os

def generate_launch_description():
    actions = []
    actions.append(Node(package='rclcpp_components', executable='component_container', name='parameter_loader_1', parameters=[os.path.join(get_package_share_directory('moveit_resources_panda_moveit_config'), 'config/sensors_kinect_pointcloud.yaml')]))
    actions.append(Node(package='rclcpp_components', executable='component_container', name='parameter_loader_2', parameters=[{'octomap_frame': 'camera_rgb_optical_frame'}]))
    actions.append(Node(package='rclcpp_components', executable='component_container', name='parameter_loader_3', parameters=[{'octomap_resolution': '0.05'}]))
    actions.append(Node(package='rclcpp_components', executable='component_container', name='parameter_loader_4', parameters=[{'max_range': '5.0'}]))
    actions.append(DeclareLaunchArgument('moveit_sensor_manager', default_value='panda'))
    actions.append(IncludeLaunchDescription(PythonLaunchDescriptionSource(os.path.join(get_package_share_directory('moveit_resources_panda_moveit_config'), 'launch/' + LaunchConfiguration('moveit_sensor_manager') + '_moveit_sensor_manager.launch.py'))))
    return LaunchDescription(actions)
