# Generated by Easy Manipulator Improved ROS 2 conversion.

import os
from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, IncludeLaunchDescription
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch.substitutions import LaunchConfiguration, PathJoinSubstitution, PythonExpression
from launch_ros.actions import Node

PACKAGE_NAME = "panda_moveit_config"


def generate_launch_description():
    package_share = get_package_share_directory(PACKAGE_NAME)
    launch_actions = []

    launch_actions.append(DeclareLaunchArgument("planning_plugin", default_value='stomp_moveit/StompPlannerManager'))
    launch_actions.append(DeclareLaunchArgument("planning_adapters", default_value='default_planner_request_adapters/AddTimeParameterization                                        default_planner_request_adapters/FixWorkspaceBounds                                        default_planner_request_adapters/FixStartStateBounds                                        default_planner_request_adapters/FixStartStateCollision                                        default_planner_request_adapters/FixStartStatePathConstraints'))
    launch_actions.append(DeclareLaunchArgument("start_state_max_bounds_error", default_value='0.1'))

    parameters = []
    parameters.append(
        {
            "planning_plugin": LaunchConfiguration("planning_plugin"),
            "request_adapters": LaunchConfiguration("planning_adapters"),
            "start_state_max_bounds_error": LaunchConfiguration("start_state_max_bounds_error"),
        }
    )
    parameters.append(os.path.join(package_share, 'config', 'stomp_planning.yaml'))

    launch_actions.append(
        Node(
            package="moveit_ros_move_group",
            executable="move_group",
            output="screen",
            parameters=parameters,
        )
    )

    return LaunchDescription(launch_actions)
