# Generated by Easy Manipulator Improved ROS 2 conversion.

from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node


def generate_launch_description():
    dev = LaunchConfiguration("dev")

    joy_node = Node(
        package="joy",
        executable="joy_node",
        name="joy",
        parameters=[
            {
                "dev": dev,
                "deadzone": 0.2,
                "autorepeat_rate": 40.0,
                "coalesce_interval": 0.025,
            }
        ],
    )

    moveit_joy = Node(
        package="moveit_ros_visualization",
        executable="moveit_joy",
        name="moveit_joy",
        output="screen",
    )

    return LaunchDescription(
        [
            DeclareLaunchArgument("dev", default_value="/dev/input/js0"),
            joy_node,
            moveit_joy,
        ]
    )
