# Generated by Easy Manipulator Improved ROS 2 conversion.

import os
from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, IncludeLaunchDescription
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch.substitutions import LaunchConfiguration, PathJoinSubstitution, PythonExpression
from launch_ros.actions import Node

PACKAGE_NAME = "robotiq_85_moveit_config"


def generate_launch_description():
    package_share = get_package_share_directory(PACKAGE_NAME)
    launch_actions = []

    parameters = []
    parameters.append(
        {
            "use_controller_manager": False,
            "trajectory_execution/execution_duration_monitoring": False,
            "moveit_controller_manager": 'moveit_simple_controller_manager/MoveItSimpleControllerManager',
        }
    )
    parameters.append(os.path.join(package_share, 'config', 'controllers.yaml'))

    launch_actions.append(
        Node(
            package="moveit_ros_move_group",
            executable="move_group",
            output="screen",
            parameters=parameters,
        )
    )

    return LaunchDescription(launch_actions)
