# Generated by Easy Manipulator Improved ROS 2 conversion.

import os
from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, IncludeLaunchDescription
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch.substitutions import LaunchConfiguration, PathJoinSubstitution, PythonExpression
from launch_ros.actions import Node

PACKAGE_NAME = "robotiq_85_moveit_config"


def generate_launch_description():
    package_share = get_package_share_directory(PACKAGE_NAME)
    launch_actions = []

    launch_actions.append(DeclareLaunchArgument("moveit_sensor_manager", default_value='robotiq_85_gripper'))

    launch_actions.append(
        IncludeLaunchDescription(
            PythonLaunchDescriptionSource(
                PathJoinSubstitution([package_share, "launch", PythonExpression(["'", "", LaunchConfiguration("moveit_sensor_manager"), "_moveit_sensor_manager.launch.py", "'"])])
            )
        )
    )

    parameters = []
    parameters.append(
        {
            "octomap_resolution": 0.025,
            "max_range": 5.0,
        }
    )

    launch_actions.append(
        Node(
            package="moveit_ros_move_group",
            executable="move_group",
            output="screen",
            parameters=parameters,
        )
    )

    return LaunchDescription(launch_actions)
