<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>run_grasp_execution</name>
  <version>0.1.0</version>
  <description>A package that provides an example node to run the emd_grasp_execution</description>
  <maintainer email="glenn_tan@artc.a-star.edu.sg">Tan Jing Peng Glenn</maintainer>
  <license>Apache License 2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>rclcpp</depend>
  <depend>rclcpp_lifecycle</depend>
  <depend>ament_index_cpp</depend>

  <depend>emd_grasp_execution</depend>
  <depend>emd_waypoint_execution</depend>

  <exec_depend>xacro</exec_depend>
  <exec_depend>visualization_msgs</exec_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>controller_manager</exec_depend>
  <exec_depend>tf2_ros</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>ur_description</exec_depend>
  <exec_depend>ur5_moveit_config</exec_depend>
  <exec_depend>robotiq_85_description</exec_depend>
  <exec_depend>robotiq_85_moveit_config</exec_depend>
  <exec_depend>workbench_description</exec_depend>
  <exec_depend>realsense2_description</exec_depend>
  <exec_depend>ur5_2f_test</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>
  <test_depend>launch_testing</test_depend>
  <test_depend>launch_testing_ament_cmake</test_depend>
  <test_depend>launch_testing_ros</test_depend>
  <test_depend>rclpy</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
