# Generated by Easy Manipulator Improved ROS 2 conversion.

from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument
from launch.conditions import IfCondition, UnlessCondition
from launch.substitutions import Command, LaunchConfiguration, PathJoinSubstitution, PythonExpression
from launch_ros.actions import Node
from launch_ros.parameter_descriptions import ParameterValue
from launch_ros.substitutions import FindPackageShare
from launch.substitutions import FindExecutable


MOVEIT_CONFIG_PACKAGE = "moveit_resources_panda_moveit_config"
DESCRIPTION_PACKAGE = "moveit_resources_panda_description"
URDF_FILE = "panda.urdf"


def generate_robot_description():
    return ParameterValue(
        Command(
            [
                FindExecutable(name="cat"),
                " ",
                PathJoinSubstitution(
                    [FindPackageShare(DESCRIPTION_PACKAGE), "urdf", URDF_FILE]
                ),
            ]
        ),
        value_type=str,
    )


def generate_robot_description_semantic(load_gripper_value):
    srdf_file = PathJoinSubstitution(
        [
            FindPackageShare(MOVEIT_CONFIG_PACKAGE),
            "config",
            PythonExpression(
                [
                    "'panda_arm_hand.srdf.xacro' if ",
                    load_gripper_value,
                    " == 'true' else 'panda_arm.srdf.xacro'",
                ]
            ),
        ]
    )
    return ParameterValue(
        Command([FindExecutable(name="xacro"), " ", srdf_file]),
        value_type=str,
    )


def generate_launch_description():
    load_gripper = LaunchConfiguration("load_gripper")

    robot_description = generate_robot_description()
    robot_description_semantic = generate_robot_description_semantic(load_gripper)

    kinematics_yaml = PathJoinSubstitution(
        [FindPackageShare(MOVEIT_CONFIG_PACKAGE), "config", "kinematics.yaml"]
    )
    joint_limits_yaml = PathJoinSubstitution(
        [FindPackageShare(MOVEIT_CONFIG_PACKAGE), "config", "joint_limits.yaml"]
    )
    ompl_planning_yaml = PathJoinSubstitution(
        [FindPackageShare(MOVEIT_CONFIG_PACKAGE), "config", "ompl_planning.yaml"]
    )

    move_group = Node(
        package="moveit_ros_move_group",
        executable="move_group",
        output="screen",
        parameters=[
            {
                "robot_description": robot_description,
                "robot_description_semantic": robot_description_semantic,
            },
            kinematics_yaml,
            joint_limits_yaml,
            ompl_planning_yaml,
            {
                "allow_trajectory_execution": LaunchConfiguration(
                    "allow_trajectory_execution"
                ),
                "max_safe_path_cost": LaunchConfiguration("max_safe_path_cost"),
                "jiggle_fraction": LaunchConfiguration("jiggle_fraction"),
                "planning_scene_monitor": {
                    "publish_planning_scene": LaunchConfiguration(
                        "publish_monitored_planning_scene"
                    ),
                    "publish_geometry_updates": LaunchConfiguration(
                        "publish_monitored_planning_scene"
                    ),
                    "publish_state_updates": LaunchConfiguration(
                        "publish_monitored_planning_scene"
                    ),
                    "publish_transforms_updates": LaunchConfiguration(
                        "publish_monitored_planning_scene"
                    ),
                },
            },
        ],
    )

    return LaunchDescription(
        [
            DeclareLaunchArgument("load_gripper", default_value="true"),
            DeclareLaunchArgument("allow_trajectory_execution", default_value="true"),
            DeclareLaunchArgument("max_safe_path_cost", default_value="1"),
            DeclareLaunchArgument("jiggle_fraction", default_value="0.05"),
            DeclareLaunchArgument(
                "publish_monitored_planning_scene", default_value="true"
            ),
            move_group,
        ]
    )
