# Generated by Easy Manipulator Improved ROS 2 conversion.

from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument
from launch.substitutions import Command, LaunchConfiguration, PathJoinSubstitution
from launch_ros.actions import Node
from launch_ros.parameter_descriptions import ParameterValue
from launch_ros.substitutions import FindPackageShare
from launch.substitutions import FindExecutable


DESCRIPTION_PACKAGE = "realsense2_description"


def generate_launch_description():
    gui = LaunchConfiguration("gui")

    robot_description = ParameterValue(
        Command(
            [
                FindExecutable(name="xacro"),
                " ",
                PathJoinSubstitution(
                    [FindPackageShare(DESCRIPTION_PACKAGE), "urdf", "test_r430_camera.urdf.xacro"]
                ),
                " ",
                "use_nominal_extrinsics:=true",
            ]
        ),
        value_type=str,
    )

    robot_state_publisher = Node(
        package="robot_state_publisher",
        executable="robot_state_publisher",
        parameters=[{"robot_description": robot_description}],
    )

    rviz = Node(
        package="rviz2",
        executable="rviz2",
        output="screen",
        arguments=[
            "-d",
            PathJoinSubstitution(
                [FindPackageShare(DESCRIPTION_PACKAGE), "rviz", "urdf.rviz"]
            ),
        ],
        parameters=[{"use_gui": gui}],
    )

    return LaunchDescription(
        [
            DeclareLaunchArgument("gui", default_value="true"),
            robot_state_publisher,
            rviz,
        ]
    )
