# Generated by Easy Manipulator Improved ROS 2 conversion.

from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument
from launch.conditions import IfCondition, UnlessCondition
from launch.substitutions import Command, LaunchConfiguration, PathJoinSubstitution
from launch_ros.actions import Node
from launch_ros.parameter_descriptions import ParameterValue
from launch_ros.substitutions import FindPackageShare
from launch.substitutions import FindExecutable


MOVEIT_CONFIG_PACKAGE = "ur10_moveit_config"
DESCRIPTION_PACKAGE = "ur_description"
ROBOT_NAME = "ur10"
URDF_FILE = "ur.urdf.xacro"
SRDF_FILE = "ur10.srdf"


def generate_robot_description(limited_value):
    return ParameterValue(
        Command(
            [
                FindExecutable(name="xacro"),
                " ",
                PathJoinSubstitution(
                    [FindPackageShare(DESCRIPTION_PACKAGE), "urdf", URDF_FILE]
                ),
                " ",
                "ur_type:=",
                ROBOT_NAME,
                " ",
                "safety_limits:=",
                limited_value,
            ]
        ),
        value_type=str,
    )


def generate_robot_description_semantic():
    return ParameterValue(
        Command(
            [
                FindExecutable(name="cat"),
                " ",
                PathJoinSubstitution(
                    [FindPackageShare(MOVEIT_CONFIG_PACKAGE), "config", SRDF_FILE]
                ),
            ]
        ),
        value_type=str,
    )


def generate_launch_description():
    limited = LaunchConfiguration("limited")
    use_gui = LaunchConfiguration("use_gui")
    use_rviz = LaunchConfiguration("use_rviz")
    rviz_config = LaunchConfiguration("rviz_config")

    robot_description = generate_robot_description(limited)
    robot_description_semantic = generate_robot_description_semantic()

    kinematics_yaml = PathJoinSubstitution(
        [FindPackageShare(MOVEIT_CONFIG_PACKAGE), "config", "kinematics.yaml"]
    )
    joint_limits_yaml = PathJoinSubstitution(
        [FindPackageShare(MOVEIT_CONFIG_PACKAGE), "config", "joint_limits.yaml"]
    )
    ompl_planning_yaml = PathJoinSubstitution(
        [FindPackageShare(MOVEIT_CONFIG_PACKAGE), "config", "ompl_planning.yaml"]
    )

    joint_state_publisher = Node(
        package="joint_state_publisher",
        executable="joint_state_publisher",
        output="screen",
        condition=UnlessCondition(use_gui),
        parameters=[
            {
                "source_list": ["move_group/fake_controller_joint_states"],
            }
        ],
    )

    joint_state_publisher_gui = Node(
        package="joint_state_publisher_gui",
        executable="joint_state_publisher_gui",
        output="screen",
        condition=IfCondition(use_gui),
    )

    robot_state_publisher = Node(
        package="robot_state_publisher",
        executable="robot_state_publisher",
        output="screen",
        parameters=[
            {"robot_description": robot_description},
        ],
    )

    move_group = Node(
        package="moveit_ros_move_group",
        executable="move_group",
        output="screen",
        parameters=[
            {
                "robot_description": robot_description,
                "robot_description_semantic": robot_description_semantic,
            },
            kinematics_yaml,
            joint_limits_yaml,
            ompl_planning_yaml,
        ],
    )

    rviz = Node(
        package="rviz2",
        executable="rviz2",
        output="screen",
        condition=IfCondition(use_rviz),
        arguments=["-d", rviz_config],
        parameters=[
            {
                "robot_description": robot_description,
                "robot_description_semantic": robot_description_semantic,
            },
            kinematics_yaml,
            joint_limits_yaml,
        ],
    )

    return LaunchDescription(
        [
            DeclareLaunchArgument("limited", default_value="false"),
            DeclareLaunchArgument("use_gui", default_value="false"),
            DeclareLaunchArgument("use_rviz", default_value="true"),
            DeclareLaunchArgument(
                "rviz_config",
                default_value=PathJoinSubstitution(
                    [FindPackageShare(MOVEIT_CONFIG_PACKAGE), "launch", "moveit.rviz"]
                ),
            ),
            joint_state_publisher,
            joint_state_publisher_gui,
            robot_state_publisher,
            move_group,
            rviz,
        ]
    )
