# Autogenerated from ROS 1 launch file.
from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, GroupAction
from launch.actions import IncludeLaunchDescription
from launch.conditions import IfCondition, UnlessCondition
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch.substitutions import Command
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node
from launch_ros.actions import PushRosNamespace
from launch_ros.parameter_descriptions import ParameterValue
import os

def generate_launch_description():
    actions = []
    actions.append(DeclareLaunchArgument('limited', default_value='false'))
    actions.append(IncludeLaunchDescription(PythonLaunchDescriptionSource(os.path.join(get_package_share_directory('ur10_moveit_config'), 'launch/planning_context.launch.py')), launch_arguments=dict([('limited', LaunchConfiguration('limited'))]).items()))
    actions.append(DeclareLaunchArgument('debug', default_value='false'))
    actions.append(DeclareLaunchArgument('launch_prefix', default_value=''))
    actions.append(DeclareLaunchArgument('launch_prefix', default_value='gdb --ex run --args'))
    actions.append(DeclareLaunchArgument('info', default_value=LaunchConfiguration('debug')))
    actions.append(DeclareLaunchArgument('command_args', default_value=''))
    actions.append(DeclareLaunchArgument('command_args', default_value='--debug'))
    actions.append(DeclareLaunchArgument('allow_trajectory_execution', default_value='true'))
    actions.append(DeclareLaunchArgument('fake_execution', default_value='false'))
    actions.append(DeclareLaunchArgument('max_safe_path_cost', default_value='1'))
    actions.append(DeclareLaunchArgument('jiggle_fraction', default_value='0.05'))
    actions.append(DeclareLaunchArgument('publish_monitored_planning_scene', default_value='true'))
    actions.append(GroupAction(actions=[PushRosNamespace('move_group'), IncludeLaunchDescription(PythonLaunchDescriptionSource(os.path.join(get_package_share_directory('ur10_moveit_config'), 'launch/planning_pipeline.launch.py')), launch_arguments=dict([('pipeline', 'ompl')]).items())]))
    actions.append(GroupAction(actions=[PushRosNamespace('move_group'), IncludeLaunchDescription(PythonLaunchDescriptionSource(os.path.join(get_package_share_directory('ur10_moveit_config'), 'launch/trajectory_execution.launch.py')), launch_arguments=dict([('moveit_manage_controllers', 'true'), ('moveit_controller_manager', 'ur10'), ('moveit_controller_manager', 'fake')]).items())], condition=IfCondition(LaunchConfiguration('allow_trajectory_execution'))))
    actions.append(GroupAction(actions=[PushRosNamespace('move_group'), IncludeLaunchDescription(PythonLaunchDescriptionSource(os.path.join(get_package_share_directory('ur10_moveit_config'), 'launch/sensor_manager.launch.py')), launch_arguments=dict([('moveit_sensor_manager', 'ur10')]).items())], condition=IfCondition(LaunchConfiguration('allow_trajectory_execution'))))
    actions.append(Node(package='moveit_ros_move_group', executable='move_group', name='move_group', output='screen', arguments=['$(arg', 'command_args)'], parameters=[{'allow_trajectory_execution': LaunchConfiguration('allow_trajectory_execution'), 'max_safe_path_cost': LaunchConfiguration('max_safe_path_cost'), 'jiggle_fraction': LaunchConfiguration('jiggle_fraction'), 'capabilities': 'move_group/MoveGroupCartesianPathService           move_group/MoveGroupExecuteTrajectoryAction           move_group/MoveGroupKinematicsService           move_group/MoveGroupMoveAction           move_group/MoveGroupPickPlaceAction           move_group/MoveGroupPlanService           move_group/MoveGroupQueryPlannersService           move_group/MoveGroupStateValidationService           move_group/MoveGroupGetPlanningSceneService           move_group/ClearOctomapService           ', 'planning_scene_monitor/publish_planning_scene': LaunchConfiguration('publish_monitored_planning_scene'), 'planning_scene_monitor/publish_geometry_updates': LaunchConfiguration('publish_monitored_planning_scene'), 'planning_scene_monitor/publish_state_updates': LaunchConfiguration('publish_monitored_planning_scene'), 'planning_scene_monitor/publish_transforms_updates': LaunchConfiguration('publish_monitored_planning_scene')}], respawn=False))
    return LaunchDescription(actions)
