# Autogenerated from ROS 1 launch file.
from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, GroupAction
from launch.actions import IncludeLaunchDescription
from launch.conditions import IfCondition, UnlessCondition
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch.substitutions import Command
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node
from launch_ros.actions import PushRosNamespace
from launch_ros.parameter_descriptions import ParameterValue
import os

def generate_launch_description():
    actions = []
    actions.append(DeclareLaunchArgument('debug', default_value='false'))
    actions.append(DeclareLaunchArgument('launch_prefix', default_value=''))
    actions.append(DeclareLaunchArgument('launch_prefix', default_value='gdb --ex run --args'))
    actions.append(DeclareLaunchArgument('config', default_value='false'))
    actions.append(DeclareLaunchArgument('command_args', default_value=''))
    actions.append(DeclareLaunchArgument('command_args', default_value=os.path.join(get_package_share_directory('ur10_moveit_config'), '-d /launch/moveit.rviz')))
    actions.append(Node(package='rviz', executable='rviz', name='$(anon rviz)', output='screen', arguments=['$(arg', 'command_args)'], parameters=[os.path.join(get_package_share_directory('ur10_moveit_config'), 'config/kinematics.yaml')], respawn=False))
    return LaunchDescription(actions)
