# Autogenerated from ROS 1 launch file.
from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, GroupAction
from launch.actions import IncludeLaunchDescription
from launch.conditions import IfCondition, UnlessCondition
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch.substitutions import Command
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node
from launch_ros.actions import PushRosNamespace
from launch_ros.parameter_descriptions import ParameterValue
import os

def generate_launch_description():
    actions = []
    actions.append(DeclareLaunchArgument('moveit_warehouse_database_path'))
    actions.append(IncludeLaunchDescription(PythonLaunchDescriptionSource(os.path.join(get_package_share_directory('ur10_moveit_config'), 'launch/warehouse_settings.launch.py'))))
    actions.append(Node(package='warehouse_ros', executable='mongo_wrapper_ros.py', name='$(anon mongo_wrapper_ros)', parameters=[{'overwrite': 'false', 'database_path': LaunchConfiguration('moveit_warehouse_database_path')}]))
    return LaunchDescription(actions)
