# Generated by Easy Manipulator Improved ROS 2 conversion.

from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, IncludeLaunchDescription
from launch.conditions import IfCondition
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch.substitutions import LaunchConfiguration, PathJoinSubstitution
from launch_ros.substitutions import FindPackageShare


MOVEIT_CONFIG_PACKAGE = "robotiq_85_moveit_config"


def generate_launch_description():
    demo = LaunchConfiguration("demo")

    return LaunchDescription(
        [
            DeclareLaunchArgument("sim", default_value="false"),
            DeclareLaunchArgument("debug", default_value="false"),
            DeclareLaunchArgument("demo", default_value="false"),
            IncludeLaunchDescription(
                PythonLaunchDescriptionSource(
                    PathJoinSubstitution(
                        [
                            FindPackageShare(MOVEIT_CONFIG_PACKAGE),
                            "launch",
                            "move_group.launch.py",
                        ]
                    )
                )
            ),
            IncludeLaunchDescription(
                PythonLaunchDescriptionSource(
                    PathJoinSubstitution(
                        [
                            FindPackageShare(MOVEIT_CONFIG_PACKAGE),
                            "launch",
                            "default_warehouse_db.launch.py",
                        ]
                    )
                ),
                condition=IfCondition(demo),
            ),
        ]
    )
