# Generated by Easy Manipulator Improved ROS 2 conversion.

from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, IncludeLaunchDescription
from launch.launch_description_sources import XMLLaunchDescriptionSource
from launch.substitutions import LaunchConfiguration, PathJoinSubstitution
from launch_ros.actions import Node
from launch_ros.substitutions import FindPackageShare


def generate_launch_description():
    database_path = LaunchConfiguration("moveit_warehouse_database_path")

    return LaunchDescription(
        [
            DeclareLaunchArgument("moveit_warehouse_database_path"),
            IncludeLaunchDescription(
                XMLLaunchDescriptionSource(
                    PathJoinSubstitution(
                        [
                            FindPackageShare("single_suction_moveit_config"),
                            "launch",
                            "warehouse_settings.launch.xml",
                        ]
                    )
                )
            ),
            Node(
                package="warehouse_ros_mongo",
                executable="mongo_wrapper_ros",
                output="screen",
                parameters=[
                    {
                        "overwrite": False,
                        "database_path": database_path,
                    }
                ],
            ),
        ]
    )
