# Generated by Easy Manipulator Improved ROS 2 conversion.

from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node


def generate_launch_description():
    database_path = LaunchConfiguration("moveit_warehouse_database_path")
    warehouse_port = LaunchConfiguration("moveit_warehouse_port")
    warehouse_host = LaunchConfiguration("moveit_warehouse_host")

    return LaunchDescription(
        [
            DeclareLaunchArgument("moveit_warehouse_database_path"),
            DeclareLaunchArgument("moveit_warehouse_port", default_value="33829"),
            DeclareLaunchArgument("moveit_warehouse_host", default_value="localhost"),
            Node(
                package="warehouse_ros_mongo",
                executable="mongo_wrapper_ros",
                output="screen",
                parameters=[
                    {
                        "overwrite": False,
                        "database_path": database_path,
                        "warehouse_port": warehouse_port,
                        "warehouse_host": warehouse_host,
                        "warehouse_plugin": "warehouse_ros_mongo::MongoDatabaseConnection",
                    }
                ],
            ),
        ]
    )
