<package format="3"><name>simple_conveyor_description</name><version>0.1.0</version><description>simple_conveyor_description</description><maintainer email="noreply@example.com">wb</maintainer><license>Apache-2.0</license><buildtool_depend>ament_cmake</buildtool_depend><export><build_type>ament_cmake</build_type></export></package>
