<?xml version="1.0"?>
<package format="3">
  <name>robotiq_85_description</name>
  <version>0.0.0</version>
  <description>Minimal description package for the Robotiq 85 gripper.</description>
  <maintainer email="devnull@example.com">Easy Manipulator</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
