#!/usr/bin/env bash
# Helpers for ensuring tesseract_motion_planners component package configs exist

# Print informational messages using existing log helpers when available
_mpc_info() {
  if declare -F log_info >/dev/null 2>&1; then
    log_info "$@"
  else
    echo "[INFO] $*"
  fi
}

# Print warning messages using existing log helpers when available
_mpc_warn() {
  if declare -F log_warn >/dev/null 2>&1; then
    log_warn "$@"
  else
    echo "[WARN] $*" >&2
  fi
}

_mpc_resolve_workspace() {
  local workspace="$1"

  if [[ -z "$workspace" ]]; then
    if [[ -n ${WORKSPACE_ROOT:-} ]]; then
      workspace="$WORKSPACE_ROOT"
    elif [[ -n ${WS:-} ]]; then
      workspace="$WS"
    fi
  fi

  [[ -n "$workspace" ]] || return 1

  cd "$workspace" >/dev/null 2>&1 || return 1
  pwd
}

ensure_motion_planners_component_config() {
  local component="$1"
  local workspace
  workspace="$(_mpc_resolve_workspace "$2")" || {
    _mpc_warn "Workspace root is unavailable; skipping config synthesis for ${component}"
    return
  }

  local install_prefix="${workspace}/install"
  local package_prefix="${install_prefix}/tesseract_motion_planners"
  local merge_layout=0

  if [[ -f "${install_prefix}/.colcon_install_layout" ]] &&
     grep -q "merged" "${install_prefix}/.colcon_install_layout"; then
    merge_layout=1
  elif [[ -d "${install_prefix}/lib/cmake/tesseract_motion_planners_${component}" ]]; then
    merge_layout=1
  fi

  if (( merge_layout )); then
    package_prefix="${install_prefix}"
  fi

  if [[ ! -d "${package_prefix}" ]]; then
    return
  fi

  local config_dir="${package_prefix}/lib/cmake/tesseract_motion_planners_${component}"
  local config_file="${config_dir}/tesseract_motion_planners_${component}Config.cmake"
  local targets_file="${config_dir}/tesseract_motion_planners_${component}Targets.cmake"

  local needs_regeneration=0
  if [[ ! -f "${config_file}" || ! -f "${targets_file}" ]]; then
    needs_regeneration=1
  elif ! grep -Eq "tesseract_motion_planners_${component}" "${config_file}" "${targets_file}"; then
    needs_regeneration=1
  fi

  if (( !needs_regeneration )); then
    return
  fi

  local lib=""
  local candidate
  for candidate in \
    "${package_prefix}/lib/libtesseract_motion_planners_${component}.so" \
    "${package_prefix}/lib/libtesseract_motion_planners_${component}.dylib" \
    "${package_prefix}/lib/tesseract_motion_planners_${component}.lib" \
    "${package_prefix}/bin/tesseract_motion_planners_${component}.dll"; do
    if [[ -f "${candidate}" ]]; then
      lib="${candidate}"
      break
    fi
  done

  if [[ -z "${lib}" ]]; then
    _mpc_warn "tesseract_motion_planners_${component} library not found under ${package_prefix}; skipping config synthesis"
    return
  fi

  local include_dir="${package_prefix}/include"
  if [[ ! -d "${include_dir}" ]]; then
    include_dir="${package_prefix}/include/tesseract_motion_planners"
  fi

  mkdir -p "${config_dir}"

  cat >"${targets_file}" <<EOF
if(NOT TARGET tesseract_motion_planners_${component})
  add_library(tesseract_motion_planners_${component} SHARED IMPORTED)
  set_target_properties(tesseract_motion_planners_${component} PROPERTIES
    IMPORTED_LOCATION "${lib}"
    INTERFACE_INCLUDE_DIRECTORIES "${include_dir}"
EOF
  if [[ "${component}" == "simple" ]]; then
    cat >>"${targets_file}" <<'EOF'
    INTERFACE_LINK_LIBRARIES "tesseract::tesseract_motion_planners_core"
EOF
  fi
  cat >>"${targets_file}" <<'EOF'
  )
endif()
if(NOT TARGET tesseract::tesseract_motion_planners_${component})
  add_library(tesseract::tesseract_motion_planners_${component} ALIAS tesseract_motion_planners_${component})
endif()
EOF

  cat >"${config_file}" <<EOF
# Generated by helper scripts to provide a minimal CMake package for
# tesseract_motion_planners_${component} when the upstream build does not install one.
include(CMakeFindDependencyMacro)
EOF

  if [[ "${component}" == "core" ]]; then
    cat >>"${config_file}" <<'EOF'
find_dependency(Eigen3)
find_dependency(console_bridge)
find_dependency(tesseract_common)
find_dependency(tesseract_environment)
find_dependency(tesseract_command_language)
find_dependency(Boost)
EOF
  else
    cat >>"${config_file}" <<'EOF'
find_dependency(tesseract_motion_planners_core)
find_dependency(tesseract_environment)
find_dependency(tesseract_command_language)
find_dependency(cereal)
find_dependency(Boost)
EOF
  fi

  cat >>"${config_file}" <<EOF
include("\${CMAKE_CURRENT_LIST_DIR}/tesseract_motion_planners_${component}Targets.cmake")
if(NOT TARGET tesseract::tesseract_motion_planners_${component})
  add_library(tesseract::tesseract_motion_planners_${component} ALIAS tesseract_motion_planners_${component})
endif()
set(tesseract_motion_planners_${component}_FOUND TRUE)
EOF

  local package_xml="${package_prefix}/share/tesseract_motion_planners/package.xml"
  local repo_root="${REPO_DIR:-${REPO_ROOT:-${workspace}/src/easy_manipulation_deployment}}"
  if [[ ! -f "${package_xml}" && -f "${repo_root}/tesseract_planning/tesseract_motion_planners/package.xml" ]]; then
    package_xml="${repo_root}/tesseract_planning/tesseract_motion_planners/package.xml"
  fi

  local version="0.0.0"
  if [[ -f "${package_xml}" ]]; then
    version="$(PACKAGE_XML="${package_xml}" python3 - <<'PY'
import os
import xml.etree.ElementTree as ET

path = os.environ["PACKAGE_XML"]
try:
    root = ET.parse(path).getroot()
except Exception:
    print("0.0.0")
else:
    text = root.findtext("version")
    print(text.strip() if text else "0.0.0")
PY
)"
    version="${version:-0.0.0}"
  fi

  local version_file="${config_dir}/tesseract_motion_planners_${component}ConfigVersion.cmake"
  local version_script
  version_script=$(mktemp)
  cat >"${version_script}" <<'EOF'
include(CMakePackageConfigHelpers)
write_basic_package_version_file("${OUTPUT_FILE}" VERSION "${PACKAGE_VERSION}" COMPATIBILITY SameMajorVersion)
EOF
  cmake -DPACKAGE_VERSION="${version}" -DOUTPUT_FILE="${version_file}" -P "${version_script}"
  rm -f "${version_script}"

  _mpc_info "Synthesized tesseract_motion_planners_${component} package configuration at ${config_dir}"
}

ensure_motion_planners_component_configs() {
  local workspace
  workspace="$(_mpc_resolve_workspace "$1")" || {
    _mpc_warn "Workspace root is unavailable; skipping motion planner config synthesis"
    return
  }

  ensure_motion_planners_component_config core "$workspace"
  ensure_motion_planners_component_config simple "$workspace"
}
