# Generated by Easy Manipulator Improved ROS 2 conversion.

from launch import LaunchDescription
from launch_ros.actions import SetParameter
from launch.substitutions import Command, PathJoinSubstitution
from launch_ros.parameter_descriptions import ParameterValue
from launch_ros.substitutions import FindPackageShare
from launch.substitutions import FindExecutable


DESCRIPTION_PACKAGE = "robotiq_3f_gripper_visualization"


def generate_launch_description():
    robot_description = ParameterValue(
        Command(
            [
                FindExecutable(name="xacro"),
                " ",
                PathJoinSubstitution(
                    [
                        FindPackageShare(DESCRIPTION_PACKAGE),
                        "cfg",
                        "robotiq-3f-gripper_articulated.xacro",
                    ]
                ),
            ]
        ),
        value_type=str,
    )

    return LaunchDescription(
        [
            SetParameter(name="robot_description", value=robot_description),
        ]
    )
