# Autogenerated from ROS 1 launch file.
from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, GroupAction
from launch.actions import IncludeLaunchDescription
from launch.conditions import IfCondition, UnlessCondition
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch.substitutions import Command
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node
from launch_ros.actions import PushRosNamespace
from launch_ros.parameter_descriptions import ParameterValue
import os

def generate_launch_description():
    actions = []
    actions.append(DeclareLaunchArgument('dev', default_value='/dev/input/js0'))
    actions.append(Node(package='joy', executable='joy_node', name='joy', parameters=[{'dev': LaunchConfiguration('dev'), 'deadzone': '0.2', 'autorepeat_rate': '40', 'coalesce_interval': '0.025'}]))
    actions.append(Node(package='moveit_ros_visualization', executable='moveit_joy.py', name='moveit_joy', output='screen'))
    return LaunchDescription(actions)
