# Generated by Easy Manipulator Improved ROS 2 conversion.

import os
from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, IncludeLaunchDescription
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch.substitutions import LaunchConfiguration, PathJoinSubstitution, PythonExpression
from launch_ros.actions import Node

PACKAGE_NAME = "onrobot_airpick4_moveit_config"


def generate_launch_description():
    package_share = get_package_share_directory(PACKAGE_NAME)
    launch_actions = []

    launch_actions.append(DeclareLaunchArgument("pipeline", default_value='ompl'))

    launch_actions.append(
        IncludeLaunchDescription(
            PythonLaunchDescriptionSource(
                PathJoinSubstitution([package_share, "launch", PythonExpression(["'", "", LaunchConfiguration("pipeline"), "_planning_pipeline.launch.py", "'"])])
            )
        )
    )

    return LaunchDescription(launch_actions)
