workcell:
  ros__parameters:
    groups: [manipulator]
    groups.manipulator.executors: [default]
    groups.manipulator.executors.default.plugin: grasp_execution/DefaultExecutor
    groups.manipulator.end_effectors: [suction_cup0]
    groups.manipulator.end_effectors.suction_cup0.brand: single_suction
    groups.manipulator.end_effectors.suction_cup0.link: ee_palm
    groups.manipulator.end_effectors.suction_cup0.clearance: 0.05
    groups.manipulator.end_effectors.suction_cup0.driver.plugin: >-
      grasp_execution/DummyGripperDriver
    groups.manipulator.end_effectors.suction_cup0.driver.controller: ""
