workcell:
  ros__parameters:
    groups: [manipulator]
    groups.manipulator.executors: [default]
    groups.manipulator.executors.default.plugin: grasp_execution/DefaultExecutor
    groups.manipulator.end_effectors: [tool0_ee]
    groups.manipulator.end_effectors.tool0_ee.brand: ur_tool0
    groups.manipulator.end_effectors.tool0_ee.link: tool0
    groups.manipulator.end_effectors.tool0_ee.clearance: 0.1
    groups.manipulator.end_effectors.tool0_ee.driver.plugin:
      grasp_execution/DummyGripperDriver
    groups.manipulator.end_effectors.tool0_ee.driver.controller: ""
