#!/usr/bin/env python3
"""Generate task recipe metadata validation report for scene manifests."""

from __future__ import annotations

import argparse
import importlib.util
import sys
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]
MANIFEST_CANDIDATES = ("scene_manifest.yaml", "workcell.yaml")
REPORT_PATH = REPO_ROOT / "docs" / "manuals" / "latest_task_recipe_report.md"
VALIDATOR_PATH = REPO_ROOT / "scripts" / "validate_scene_contract.py"


def _load_validator_module():
    spec = importlib.util.spec_from_file_location("validate_scene_contract", VALIDATOR_PATH)
    if not spec or not spec.loader:
        raise RuntimeError(f"Unable to load validator module from {VALIDATOR_PATH}")
    module = importlib.util.module_from_spec(spec)
    sys.modules["validate_scene_contract"] = module
    spec.loader.exec_module(module)
    return module


validator = _load_validator_module()


@dataclass
class TaskRecipeRow:
    scene: str
    recipe_id: str
    task_type: str
    enabled: str
    decision_rules: int
    destinations: int
    status: str
    notes: str


def discover_scene_manifests() -> list[tuple[str, Path]]:
    scenes_dir = REPO_ROOT / "scenes"
    if not scenes_dir.is_dir():
        return []

    discovered: list[tuple[str, Path]] = []
    for entry in sorted(scenes_dir.iterdir()):
        if not entry.is_dir():
            continue
        for candidate in MANIFEST_CANDIDATES:
            path = entry / candidate
            if path.is_file():
                discovered.append((entry.name, path))
                break
    return discovered


def _to_int_length(value: Any) -> int:
    return len(value) if isinstance(value, list) else 0


def evaluate_scene(scene_name: str, manifest_path: Path) -> TaskRecipeRow:
    try:
        manifest, _, parser_notes = validator._read_manifest(str(manifest_path))
    except Exception as exc:  # pragma: no cover
        return TaskRecipeRow(
            scene=scene_name,
            recipe_id="(n/a)",
            task_type="(n/a)",
            enabled="(n/a)",
            decision_rules=0,
            destinations=0,
            status="FAIL",
            notes=f"Manifest parse failed: {exc}",
        )

    status, validation_notes = validator.validate_task_recipe_block(manifest)
    task_recipe = manifest.get("task_recipe") if isinstance(manifest.get("task_recipe"), dict) else {}

    decision_rules = _to_int_length(task_recipe.get("decision_rules"))
    destinations = _to_int_length(task_recipe.get("destinations"))
    recipe_id = str(task_recipe.get("id", "(n/a)"))
    task_type = str(task_recipe.get("type", "(n/a)"))
    enabled = str(task_recipe.get("enabled", "(n/a)"))

    notes = parser_notes + validation_notes
    return TaskRecipeRow(
        scene=scene_name,
        recipe_id=recipe_id,
        task_type=task_type,
        enabled=enabled,
        decision_rules=decision_rules,
        destinations=destinations,
        status=status,
        notes="; ".join(notes),
    )


def build_report(rows: list[TaskRecipeRow]) -> str:
    timestamp = datetime.now(timezone.utc).isoformat()
    lines = [
        "# Latest Task Recipe Report",
        "",
        f"- Generated (UTC): `{timestamp}`",
        f"- Repository: `{REPO_ROOT}`",
        "",
        "## Scene task recipe status",
        "",
        "| scene | task recipe id | task type | enabled | decision rules | destinations | status | notes / next action |",
        "|---|---|---|---|---|---|---|---|",
    ]

    for row in rows:
        lines.append(
            f"| `{row.scene}` | `{row.recipe_id}` | `{row.task_type}` | `{row.enabled}` | "
            f"{row.decision_rules} | {row.destinations} | **{row.status}** | {row.notes} |"
        )

    pass_count = sum(1 for row in rows if row.status == "PASS")
    warn_count = sum(1 for row in rows if row.status == "WARN")
    fail_count = sum(1 for row in rows if row.status == "FAIL")

    lines.extend(
        [
            "",
            "## Summary",
            "",
            f"- PASS: {pass_count}",
            f"- WARN: {warn_count}",
            f"- FAIL: {fail_count}",
            "",
            "Generated by `./scripts/generate_task_recipe_report.py`.",
        ]
    )

    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("scenes", nargs="*", help="Optional scene names to include.")
    parser.add_argument("--check", action="store_true", help="Print PASS/WARN/FAIL summary to stdout.")
    args = parser.parse_args()

    discovered = discover_scene_manifests()
    if args.scenes:
        requested = set(args.scenes)
        discovered = [entry for entry in discovered if entry[0] in requested]

    if not discovered:
        print("No scene manifests discovered for task recipe reporting.")
        return 2

    rows = [evaluate_scene(scene, path) for scene, path in discovered]

    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    REPORT_PATH.write_text(build_report(rows), encoding="utf-8")
    print(f"Wrote task recipe report: {REPORT_PATH}")

    if args.check:
        for row in rows:
            print(f"{row.status:4} {row.scene:24} {row.notes}")
        pass_count = sum(1 for row in rows if row.status == "PASS")
        warn_count = sum(1 for row in rows if row.status == "WARN")
        fail_count = sum(1 for row in rows if row.status == "FAIL")
        print(f"Summary: PASS={pass_count} WARN={warn_count} FAIL={fail_count}")

    return 1 if any(row.status == "FAIL" for row in rows) else 0


if __name__ == "__main__":
    raise SystemExit(main())
