#!/usr/bin/env python3
"""Generate markdown report from smoke launch scene results."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
import argparse
import os
import subprocess

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_RESULTS_PATH = REPO_ROOT / "docs" / "manuals" / "latest_smoke_launch_results.tsv"
REPORT_PATH = REPO_ROOT / "docs" / "manuals" / "latest_smoke_launch_report.md"
SMOKE_SCRIPT = REPO_ROOT / "scripts" / "smoke_launch_scenes.sh"


@dataclass
class SmokeRow:
    scene: str
    status: str
    markers_found: str
    notes: str
    log_path: str


def parse_smoke_results(results_text: str) -> list[SmokeRow]:
    rows: list[SmokeRow] = []
    for raw in results_text.splitlines():
        line = raw.strip()
        if not line:
            continue
        parts = line.split("\t")
        while len(parts) < 5:
            parts.append("")
        rows.append(
            SmokeRow(
                scene=parts[0],
                status=parts[1],
                markers_found=parts[2],
                notes=parts[3],
                log_path=parts[4],
            )
        )
    return rows


def summarize(rows: list[SmokeRow]) -> tuple[int, int, int]:
    pass_count = sum(1 for row in rows if row.status == "PASS")
    fail_count = sum(1 for row in rows if row.status == "FAIL")
    skip_count = sum(1 for row in rows if row.status == "SKIP")
    return pass_count, fail_count, skip_count


def resolve_workspace_hint() -> str:
    for key in ("WORKCELL_WS", "WORKSPACE", "COLCON_CURRENT_PREFIX"):
        value = os.environ.get(key)
        if value:
            return value
    return str(Path.cwd())


def run_smoke_script(timeout_sec: int) -> int:
    completed = subprocess.run(
        [str(SMOKE_SCRIPT)],
        cwd=REPO_ROOT,
        text=True,
        capture_output=True,
        check=False,
        env={**os.environ, "SCENE_TIMEOUT_SEC": str(timeout_sec)},
    )
    if completed.stdout:
        print(completed.stdout, end="")
    if completed.stderr:
        print(completed.stderr, end="")
    return completed.returncode


def build_report(rows: list[SmokeRow], results_path: Path) -> str:
    timestamp = datetime.now(timezone.utc).isoformat()
    workspace_hint = resolve_workspace_hint()
    pass_count, fail_count, skip_count = summarize(rows)

    if fail_count > 0:
        next_action = "- FAIL detected: inspect the smoke log for each failed scene and fix launch/readiness blockers."
    elif skip_count > 0:
        next_action = "- SKIP detected: source the workspace and rebuild/install scene packages, then rerun smoke preflight."
    else:
        next_action = "- PASS: proceed to planner/perception integration tests."

    lines = [
        "# Latest Smoke Launch Report",
        "",
        f"- Generated (UTC): `{timestamp}`",
        f"- Repository: `{REPO_ROOT}`",
        f"- Workspace hint: `{workspace_hint}`",
        f"- Results source: `{results_path}`",
        "",
        "## Scene launch readiness results",
        "",
        "| scene | status | readiness markers found | notes |",
        "|---|---|---|---|",
    ]

    for row in rows:
        marker_text = row.markers_found or "(none)"
        note = row.notes
        if row.log_path:
            note = f"{note}; log: `{row.log_path}`" if note else f"log: `{row.log_path}`"
        lines.append(f"| `{row.scene}` | **{row.status}** | {marker_text} | {note} |")

    lines.extend(
        [
            "",
            "## Summary",
            "",
            f"- PASS: {pass_count}",
            f"- FAIL: {fail_count}",
            f"- SKIP: {skip_count}",
            "",
            "## Next action",
            "",
            next_action,
            "",
            "Generated by `./scripts/generate_smoke_launch_report.py`.",
        ]
    )

    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--run", action="store_true", help="Run smoke launch script before generating report.")
    parser.add_argument("--timeout", type=int, default=30, help="Timeout in seconds to pass to smoke script when --run is used.")
    parser.add_argument(
        "--results",
        default=str(DEFAULT_RESULTS_PATH),
        help="Path to smoke results TSV generated by smoke_launch_scenes.sh",
    )
    args = parser.parse_args()

    results_path = Path(args.results)

    smoke_exit_code = 0
    if args.run:
        smoke_exit_code = run_smoke_script(timeout_sec=args.timeout)

    if not results_path.exists():
        print(f"Smoke results file not found: {results_path}")
        return 2 if smoke_exit_code == 0 else smoke_exit_code

    rows = parse_smoke_results(results_path.read_text(encoding="utf-8"))
    if not rows:
        print(f"Smoke results file is empty: {results_path}")
        return 2 if smoke_exit_code == 0 else smoke_exit_code

    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    REPORT_PATH.write_text(build_report(rows, results_path), encoding="utf-8")
    print(f"Wrote smoke launch report: {REPORT_PATH}")

    _, fail_count, _ = summarize(rows)
    if fail_count > 0:
        return 1

    return smoke_exit_code


if __name__ == "__main__":
    raise SystemExit(main())
