#!/usr/bin/env python3
"""Generate offline task recipe dry-run report for scene manifests."""

from __future__ import annotations

import argparse
import importlib.util
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
REPORT_PATH = REPO_ROOT / "docs" / "manuals" / "latest_task_recipe_dry_run_report.md"
DRY_RUN_PATH = REPO_ROOT / "scripts" / "dry_run_task_recipe.py"


def _load_dry_run_module():
    spec = importlib.util.spec_from_file_location("dry_run_task_recipe", DRY_RUN_PATH)
    if not spec or not spec.loader:
        raise RuntimeError(f"Unable to load dry-run module from {DRY_RUN_PATH}")
    module = importlib.util.module_from_spec(spec)
    sys.modules["dry_run_task_recipe"] = module
    spec.loader.exec_module(module)
    return module


dry_run = _load_dry_run_module()


def _attr_summary(attrs: dict[str, object]) -> str:
    if not attrs:
        return "(n/a)"
    return ", ".join(f"{key}={attrs[key]}" for key in sorted(attrs.keys()))


def build_report(rows: list[object]) -> str:
    timestamp = datetime.now(timezone.utc).isoformat()
    lines = [
        "# Latest Task Recipe Dry-Run Report",
        "",
        f"- Generated (UTC): `{timestamp}`",
        f"- Repository: `{REPO_ROOT}`",
        "",
        "## Scene task recipe dry-run status",
        "",
        "| scene | status | task_recipe id | task type | self_test object id | object attributes | matched rule id | selected destination id | selected action | notes / next action |",
        "|---|---|---|---|---|---|---|---|---|---|",
    ]

    for row in rows:
        lines.append(
            f"| `{row.scene}` | **{row.status}** | `{row.recipe_id}` | `{row.task_type}` | "
            f"`{row.object_id}` | `{_attr_summary(row.object_attributes)}` | `{row.matched_rule_id}` | "
            f"`{row.selected_destination_id}` | `{row.selected_action}` | {'; '.join(row.notes)} |"
        )

    pass_count = sum(1 for row in rows if row.status == "PASS")
    warn_count = sum(1 for row in rows if row.status == "WARN")
    fail_count = sum(1 for row in rows if row.status == "FAIL")
    skip_count = sum(1 for row in rows if row.status == "SKIP")

    lines.extend(
        [
            "",
            "## Summary",
            "",
            f"- PASS: {pass_count}",
            f"- WARN: {warn_count}",
            f"- FAIL: {fail_count}",
            f"- SKIP: {skip_count}",
            "",
            "## Scope and limits",
            "",
            "The dry-run proves recipe decision logic and metadata completeness.",
            "It does not prove robot reachability, collision-free motion, grasp success, perception accuracy, or hardware execution.",
            "",
            "Generated by `./scripts/generate_task_recipe_dry_run_report.py`.",
        ]
    )

    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("scenes", nargs="*", help="Optional scene names to include.")
    parser.add_argument("--check", action="store_true", help="Print PASS/WARN/FAIL/SKIP summary to stdout.")
    args = parser.parse_args()

    discovered = dry_run.discover_scene_manifests()
    if args.scenes:
        requested = set(args.scenes)
        discovered = [entry for entry in discovered if entry[0] in requested]

    if not discovered:
        print("No scene manifests discovered for task recipe dry-run reporting.")
        return 2

    rows = [dry_run.evaluate_scene(scene, path) for scene, path in discovered]

    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    REPORT_PATH.write_text(build_report(rows), encoding="utf-8")
    print(f"Wrote task recipe dry-run report: {REPORT_PATH}")

    if args.check:
        for row in rows:
            print(f"{row.status:4} {row.scene:24} {'; '.join(row.notes)}")
        pass_count = sum(1 for row in rows if row.status == "PASS")
        warn_count = sum(1 for row in rows if row.status == "WARN")
        fail_count = sum(1 for row in rows if row.status == "FAIL")
        skip_count = sum(1 for row in rows if row.status == "SKIP")
        print(f"Summary: PASS={pass_count} WARN={warn_count} FAIL={fail_count} SKIP={skip_count}")

    return 1 if any(row.status == "FAIL" for row in rows) else 0


if __name__ == "__main__":
    raise SystemExit(main())
