#!/usr/bin/env python3
"""Generate offline task execution plan summary report."""

from __future__ import annotations

import argparse
import importlib.util
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
REPORT_PATH = REPO_ROOT / "docs" / "manuals" / "latest_task_execution_plan_report.md"
PLAN_GENERATOR_PATH = REPO_ROOT / "scripts" / "generate_task_execution_plan.py"



def _load_plan_generator_module():
    spec = importlib.util.spec_from_file_location("generate_task_execution_plan", PLAN_GENERATOR_PATH)
    if not spec or not spec.loader:
        raise RuntimeError(f"Unable to load execution plan module from {PLAN_GENERATOR_PATH}")
    module = importlib.util.module_from_spec(spec)
    sys.modules["generate_task_execution_plan"] = module
    spec.loader.exec_module(module)
    return module


plan_generator = _load_plan_generator_module()


def build_report(rows: list[object]) -> str:
    timestamp = datetime.now(timezone.utc).isoformat()
    lines = [
        "# Latest Task Execution Plan Report",
        "",
        f"- Generated (UTC): `{timestamp}`",
        f"- Repository/workspace hint: `{REPO_ROOT}`",
        "",
        "## Scene execution plan status",
        "",
        "| scene | status | task_recipe id | matched rule | destination | generated markdown path | generated json path | notes |",
        "|---|---|---|---|---|---|---|---|",
    ]

    for row in rows:
        md_path = str(row.markdown_path) if row.markdown_path else "(none)"
        json_path = str(row.json_path) if row.json_path else "(none)"
        lines.append(
            f"| `{row.scene}` | **{row.status}** | `{row.task_recipe_id}` | `{row.matched_rule_id}` | `{row.destination_id}` | "
            f"`{md_path}` | `{json_path}` | {'; '.join(row.notes)} |"
        )

    pass_count = sum(1 for row in rows if row.status == "PASS")
    warn_count = sum(1 for row in rows if row.status == "WARN")
    fail_count = sum(1 for row in rows if row.status == "FAIL")
    skip_count = sum(1 for row in rows if row.status == "SKIP")

    lines.extend(
        [
            "",
            "## Summary",
            "",
            f"- PASS: {pass_count}",
            f"- WARN: {warn_count}",
            f"- FAIL: {fail_count}",
            f"- SKIP: {skip_count}",
            "",
            "## Scope and limits",
            "",
            "This execution plan proves that the scene metadata and task recipe can be converted into a deterministic operator-readable job sequence.",
            "It does not prove reachability, collision-free planning, perception accuracy, grasp success, cycle time, safety validation, or real hardware behaviour.",
            "",
            "Generated by `./scripts/generate_task_execution_plan_report.py`.",
        ]
    )

    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("scenes", nargs="*", help="Optional scene names to include.")
    parser.add_argument("--check", action="store_true", help="Print concise PASS/WARN/FAIL/SKIP summary.")
    args = parser.parse_args()

    discovered = plan_generator.dry_run.discover_scene_manifests()
    if args.scenes:
        requested = set(args.scenes)
        discovered = [entry for entry in discovered if entry[0] in requested]

    if not discovered:
        print("No scene manifests discovered for task execution plan reporting.")
        return 2

    rows = [plan_generator.evaluate_scene(scene, path) for scene, path in discovered]

    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    REPORT_PATH.write_text(build_report(rows), encoding="utf-8")
    print(f"Wrote task execution plan report: {REPORT_PATH}")

    if args.check:
        for row in rows:
            print(f"{row.status:4} {row.scene:24} {'; '.join(row.notes)}")
        pass_count = sum(1 for row in rows if row.status == "PASS")
        warn_count = sum(1 for row in rows if row.status == "WARN")
        fail_count = sum(1 for row in rows if row.status == "FAIL")
        skip_count = sum(1 for row in rows if row.status == "SKIP")
        print(f"Summary: PASS={pass_count} WARN={warn_count} FAIL={fail_count} SKIP={skip_count}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
