#!/usr/bin/env python3
"""Generate a markdown report for scene manifest contract validation."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
import os
import subprocess

REPO_ROOT = Path(__file__).resolve().parents[1]
MANIFEST_CANDIDATES = ("scene_manifest.yaml", "workcell.yaml")
VALIDATOR = REPO_ROOT / "scripts" / "validate_scene_contract.py"
REPORT_PATH = REPO_ROOT / "docs" / "manuals" / "latest_scene_validation_report.md"


@dataclass
class SceneReportRow:
    scene: str
    status: str
    notes: str


def discover_scene_packages() -> list[str]:
    scenes_dir = REPO_ROOT / "scenes"
    if not scenes_dir.is_dir():
        return []

    packages: list[str] = []
    for entry in sorted(scenes_dir.iterdir()):
        if not entry.is_dir():
            continue
        if any((entry / candidate).is_file() for candidate in MANIFEST_CANDIDATES):
            packages.append(entry.name)
    return packages


def summarize_note(text: str, fallback: str) -> str:
    content = text.replace("\n", " ").strip()
    if not content:
        return fallback
    return content if len(content) <= 160 else f"{content[:157]}..."


def resolve_workspace_hint() -> str:
    for key in ("WORKCELL_WS", "WORKSPACE", "COLCON_CURRENT_PREFIX"):
        value = os.environ.get(key)
        if value:
            return value
    return str(Path.cwd())


def validate_scene(package: str) -> SceneReportRow:
    if not VALIDATOR.exists():
        return SceneReportRow(package, "FAIL", f"Missing validator at {VALIDATOR}")

    completed = subprocess.run(
        [str(VALIDATOR), package],
        cwd=REPO_ROOT,
        text=True,
        capture_output=True,
        check=False,
    )
    output = (completed.stdout or "") + (completed.stderr or "")

    if completed.returncode == 0:
        return SceneReportRow(package, "PASS", "Manifest contract validated.")

    if completed.returncode == 3:
        return SceneReportRow(
            package,
            "SKIP",
            summarize_note(output, "Scene package not discoverable in current environment."),
        )

    if "Missing PyYAML" in output:
        return SceneReportRow(
            package,
            "SKIP",
            "Validation dependency missing (PyYAML). Source ROS/workspace environment and rerun.",
        )

    return SceneReportRow(
        package,
        "FAIL",
        summarize_note(output, "Manifest contract validation failed."),
    )


def main() -> int:
    packages = discover_scene_packages()
    if not packages:
        print("No scene packages found under ./scenes; report not generated.")
        return 2

    rows = [validate_scene(package) for package in packages]

    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)

    timestamp = datetime.now(timezone.utc).isoformat()
    workspace_hint = resolve_workspace_hint()

    lines = [
        "# Latest Scene Validation Report",
        "",
        f"- Generated (UTC): `{timestamp}`",
        f"- Repository: `{REPO_ROOT}`",
        f"- Workspace hint: `{workspace_hint}`",
        "",
        "## Scene contract results",
        "",
        "| Scene | Result | Notes |",
        "|---|---|---|",
    ]

    for row in rows:
        lines.append(f"| `{row.scene}` | **{row.status}** | {row.notes} |")

    lines.extend(
        [
            "",
            "## Summary",
            "",
            f"- PASS: {sum(1 for row in rows if row.status == 'PASS')}",
            f"- FAIL: {sum(1 for row in rows if row.status == 'FAIL')}",
            f"- SKIP: {sum(1 for row in rows if row.status == 'SKIP')}",
            "",
            "Generated by `./scripts/generate_scene_validation_report.py`.",
        ]
    )

    REPORT_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote scene validation report: {REPORT_PATH}")

    return 1 if any(row.status == "FAIL" for row in rows) else 0


if __name__ == "__main__":
    raise SystemExit(main())
