#!/usr/bin/env python3
"""Offline checks for scenes generated by workcell_builder."""
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

import sys

SCRIPT_DIR = Path(__file__).resolve().parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

from capability_registry import load_structured_data
import subprocess


def _load_yaml_like(path: Path) -> dict[str, Any]:
    data, _ = load_structured_data(path)
    return data


def _find_task_intent(scene_path: Path) -> Path | None:
    for rel in ["generated/workcell_builder_task_intent.yaml", "workcell_builder_task_intent.yaml"]:
        cand = scene_path / rel
        if cand.is_file():
            return cand
    return None


def _run_generated_validator(path: Path, validator_name: str) -> tuple[dict[str, Any], str | None]:
    run = subprocess.run(
        ["python3", str(SCRIPT_DIR / validator_name), str(path), "--json"],
        capture_output=True,
        text=True,
        check=False,
    )
    try:
        report = json.loads(run.stdout) if run.stdout.strip() else {}
    except json.JSONDecodeError as exc:
        report = {}
        return report, f"{path.relative_to(path.parent.parent)} validator returned invalid JSON: {exc}"

    if run.returncode != 0 or report.get("result") == "FAIL":
        details = report.get("errors") if isinstance(report.get("errors"), list) else []
        detail = "; ".join(str(item) for item in details if str(item).strip())
        if not detail:
            detail = run.stderr.strip() or run.stdout.strip() or f"exit code {run.returncode}"
        return report, f"{path.relative_to(path.parent.parent)} validation failed: {detail}"
    return report, None


def validate_scene(scene_path: Path, *, require_generated: bool = False) -> dict[str, Any]:
    checks: list[dict[str, Any]] = []
    warnings: list[str] = []
    errors: list[str] = []

    for required in ("package.xml", "CMakeLists.txt", "environment.yaml"):
        exists = (scene_path / required).is_file()
        checks.append({"check": f"{required} exists", "ok": exists})
        if not exists:
            errors.append(f"Missing required file: {required}")

    env: dict[str, Any] = {}
    if (scene_path / "environment.yaml").is_file():
        env = _load_yaml_like(scene_path / "environment.yaml")

    metadata_path = scene_path / "workcell_builder_metadata.yaml"
    metadata = _load_yaml_like(metadata_path) if metadata_path.is_file() else {}
    checks.append({"check": "workcell_builder_metadata.yaml present", "ok": metadata_path.is_file(), "optional": True})
    if not metadata_path.is_file():
        warnings.append("workcell_builder_metadata.yaml missing (optional)")

    robot = env.get("robot", {}) if isinstance(env.get("robot"), dict) else {}
    ee = env.get("end_effector", {}) if isinstance(env.get("end_effector"), dict) else {}
    objects = env.get("objects", {}) if isinstance(env.get("objects"), dict) else {}

    if not robot:
        warnings.append("Robot metadata not present in environment.yaml")
    if not ee:
        warnings.append("End-effector metadata not present in environment.yaml")

    for obj_name, obj in objects.items():
        if isinstance(obj, dict) and isinstance(obj.get("filepath"), str):
            if not (scene_path / obj["filepath"]).exists():
                warnings.append(f"Object '{obj_name}' references missing asset path '{obj['filepath']}'")


    exported_cell = scene_path / "generated" / "cell_definition.yaml"
    exported_layout = scene_path / "generated" / "environment_layout.yaml"
    checks.append({"check": "generated/cell_definition.yaml present", "ok": exported_cell.is_file(), "optional": not require_generated})
    checks.append({"check": "generated/environment_layout.yaml present", "ok": exported_layout.is_file(), "optional": not require_generated})
    export_validation = {}
    if exported_cell.is_file():
        export_validation["cell_definition"], failure = _run_generated_validator(
            exported_cell, "validate_cell_definition.py"
        )
        if failure:
            errors.append(failure)
    else:
        message = "generated/cell_definition.yaml missing; run ./generated/export_workcell_studio_sources.sh"
        (errors if require_generated else warnings).append(message)
    if exported_layout.is_file():
        export_validation["environment_layout"], failure = _run_generated_validator(
            exported_layout, "validate_environment_layout.py"
        )
        if failure:
            errors.append(failure)
    else:
        message = "generated/environment_layout.yaml missing; run ./generated/export_workcell_studio_sources.sh"
        (errors if require_generated else warnings).append(message)

    task_intent_report = {}
    task_flow_summary: dict[str, Any] = {}
    task_intent_check = {"check": "generated/workcell_builder_task_intent.yaml present", "ok": False, "optional": True}
    task_intent_path = _find_task_intent(scene_path)
    if task_intent_path:
        task_intent_check["ok"] = True
        run = subprocess.run(["python3", str(SCRIPT_DIR / "validate_builder_task_intent.py"), str(task_intent_path), "--scene-package", str(scene_path), "--json"], capture_output=True, text=True, check=False)
        task_intent_report = json.loads(run.stdout) if run.stdout.strip() else {"status": "FAIL", "errors": [run.stderr.strip()]}
        if task_intent_report.get("status") == "FAIL":
            missing = task_intent_report.get("missing_required_fields", [])
            if missing:
                mapping = {
                    "pick.source.id": "pick source missing",
                    "grasp.strategy_ref": "grasp strategy missing",
                    "place.target.id": "place target missing",
                }
                for m in missing:
                    warnings.append(mapping.get(m, f"task intent missing: {m}"))
                if not ((task_intent_report.get("task_intent", {}).get("place") or {}).get("release_strategy")):
                    warnings.append("release strategy missing")
                if not ((task_intent_report.get("task_intent", {}).get("routing") or {}).get("rules")):
                    warnings.append("routing rule missing")
            else:
                errors.extend(task_intent_report.get("errors", []))
        elif task_intent_report.get("status") == "WARN":
            warnings.extend(task_intent_report.get("warnings", []))
        flow_cmd = ["python3", str(SCRIPT_DIR / "summarize_task_flow.py"), "--task-intent", str(task_intent_path), "--environment-layout", str(exported_layout if exported_layout.is_file() else (scene_path / "environment_layout.yaml")), "--json"]
        flow_run = subprocess.run(flow_cmd, capture_output=True, text=True, check=False)
        task_flow_summary = json.loads(flow_run.stdout) if flow_run.stdout.strip() else {}
        vr = task_flow_summary.get("visual_resolution", {}) if isinstance(task_flow_summary, dict) else {}
        if not vr.get("pick_coordinates_resolved", False):
            warnings.append("pick coordinates could not be resolved from scene/layout metadata")
        if not vr.get("place_coordinates_resolved", False):
            warnings.append("place coordinates could not be resolved from scene/layout metadata")
    else:
        warnings.append("Task intent missing: physical scene only.")
    checks.append(task_intent_check)

    runtime_supported = bool(metadata.get("runtime_supported", False))
    preview_only = bool(metadata.get("preview_only", False))
    fake_hw_ready = bool(metadata.get("fake_hardware_ready", True))

    suggested_actions=[]
    if not task_intent_path:
        readiness = "physical_scene_only"
        suggested_actions.append('Create builder task intent to define pick/place/grasp.')
    elif task_intent_report.get("status") == "FAIL":
        if task_intent_report.get("missing_required_fields"):
            readiness = "physical_scene_only"
            suggested_actions.append('Complete missing required task intent fields.')
        else:
            readiness = "task_intent_incomplete"
            suggested_actions.append('Complete invalid task intent errors.')
    elif (scene_path / "generated" / "task_recipe_from_builder_intent.yaml").is_file():
        readiness = "task_recipe_generated"
    else:
        readiness = "task_intent_ready_offline"
        suggested_actions.append('Generate task recipe from builder task intent.')
    if preview_only:
        readiness_runtime = "preview_only"
    elif not runtime_supported and fake_hw_ready:
        readiness_runtime = "runtime_blocked_or_preview_only"
    else:
        readiness_runtime = "runtime_possible"

    return {
        "scene_path": str(scene_path),
        "ok": len(errors) == 0,
        "readiness": readiness,
        "readiness_classification": readiness,
        "suggested_next_actions": suggested_actions,
        "runtime_readiness": readiness_runtime,
        "checks": checks,
        "warnings": warnings,
        "errors": errors,
        "export_validation": export_validation,
        "task_intent": task_intent_report,
        "task_flow_summary": task_flow_summary,
        "discovered": {
            "robot_name": robot.get("name"),
            "end_effector_name": ee.get("name"),
            "object_count": len(objects),
            "robot_capability_id": metadata.get("robot_capability_id"),
            "end_effector_capability_id": metadata.get("end_effector_capability_id"),
            "grasp_strategy_id": metadata.get("grasp_strategy_id"),
            "sensor_capability_id": metadata.get("sensor_capability_id"),
        },
    }


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("scene_path", type=Path)
    ap.add_argument("--json", action="store_true")
    ap.add_argument(
        "--require-generated",
        action="store_true",
        help="Require both canonical generated handoffs and fail when either is missing or invalid.",
    )
    args = ap.parse_args()

    report = validate_scene(args.scene_path, require_generated=args.require_generated)
    if args.json:
        print(json.dumps(report, indent=2))
    else:
        print(f"Scene: {report['scene_path']}")
        print(f"Readiness: {report['readiness']}")
        for c in report["checks"]:
            if c["ok"]:
                state = "PASS"
            elif c.get("optional"):
                state = "WARN"
            else:
                state = "FAIL"
            print(f" - {state}: {c['check']}")
        for w in report["warnings"]:
            print(f" - WARN: {w}")
        for e in report["errors"]:
            print(f" - FAIL: {e}")
    return 0 if report["ok"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
