#!/usr/bin/env python3
"""Offline checks for scenes generated by workcell_builder."""
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

import sys

SCRIPT_DIR = Path(__file__).resolve().parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

from capability_registry import load_structured_data


def _load_yaml_like(path: Path) -> dict[str, Any]:
    data, _ = load_structured_data(path)
    return data


def validate_scene(scene_path: Path) -> dict[str, Any]:
    checks: list[dict[str, Any]] = []
    warnings: list[str] = []
    errors: list[str] = []

    for required in ("package.xml", "CMakeLists.txt", "environment.yaml"):
        exists = (scene_path / required).is_file()
        checks.append({"check": f"{required} exists", "ok": exists})
        if not exists:
            errors.append(f"Missing required file: {required}")

    env: dict[str, Any] = {}
    if (scene_path / "environment.yaml").is_file():
        env = _load_yaml_like(scene_path / "environment.yaml")

    metadata_path = scene_path / "workcell_builder_metadata.yaml"
    metadata = _load_yaml_like(metadata_path) if metadata_path.is_file() else {}
    checks.append({"check": "workcell_builder_metadata.yaml present (optional)", "ok": metadata_path.is_file()})

    robot = env.get("robot", {}) if isinstance(env.get("robot"), dict) else {}
    ee = env.get("end_effector", {}) if isinstance(env.get("end_effector"), dict) else {}
    objects = env.get("objects", {}) if isinstance(env.get("objects"), dict) else {}

    if not robot:
        warnings.append("Robot metadata not present in environment.yaml")
    if not ee:
        warnings.append("End-effector metadata not present in environment.yaml")

    for obj_name, obj in objects.items():
        if isinstance(obj, dict) and isinstance(obj.get("filepath"), str):
            if not (scene_path / obj["filepath"]).exists():
                warnings.append(f"Object '{obj_name}' references missing asset path '{obj['filepath']}'")

    runtime_supported = bool(metadata.get("runtime_supported", False))
    preview_only = bool(metadata.get("preview_only", False))
    fake_hw_ready = bool(metadata.get("fake_hardware_ready", True))

    if preview_only:
        readiness = "preview_only"
    elif runtime_supported:
        readiness = "runtime_ready"
    else:
        readiness = "fake_hardware_ready" if fake_hw_ready else "preview_only"

    return {
        "scene_path": str(scene_path),
        "ok": len(errors) == 0,
        "readiness": readiness,
        "checks": checks,
        "warnings": warnings,
        "errors": errors,
        "discovered": {
            "robot_name": robot.get("name"),
            "end_effector_name": ee.get("name"),
            "object_count": len(objects),
            "robot_capability_id": metadata.get("robot_capability_id"),
            "end_effector_capability_id": metadata.get("end_effector_capability_id"),
            "grasp_strategy_id": metadata.get("grasp_strategy_id"),
            "sensor_capability_id": metadata.get("sensor_capability_id"),
        },
    }


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("scene_path", type=Path)
    ap.add_argument("--json", action="store_true")
    args = ap.parse_args()

    report = validate_scene(args.scene_path)
    if args.json:
        print(json.dumps(report, indent=2))
    else:
        print(f"Scene: {report['scene_path']}")
        print(f"Readiness: {report['readiness']}")
        for c in report["checks"]:
            print(f" - {'PASS' if c['ok'] else 'FAIL'}: {c['check']}")
        for w in report["warnings"]:
            print(f" - WARN: {w}")
        for e in report["errors"]:
            print(f" - FAIL: {e}")
    return 0 if report["ok"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
