# Generated by Easy Manipulator Improved ROS 2 conversion.


from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument
from launch.conditions import IfCondition, UnlessCondition
from launch.substitutions import LaunchConfiguration, PathJoinSubstitution
from launch_ros.actions import Node
from launch_ros.substitutions import FindPackageShare
from moveit_configs_utils import MoveItConfigsBuilder


PACKAGE_NAME = "ur3_moveit_config"
ROBOT_NAME = "ur3"
DESCRIPTION_PACKAGE = "ur_description"
URDF_PATH = ['urdf', 'ur.urdf.xacro']
SRDF_PATH = ['config', 'ur3.srdf']
URDF_MAPPINGS = {'ur_type': 'ur3'}


def build_moveit_config():
    return (
        MoveItConfigsBuilder(ROBOT_NAME, package_name=PACKAGE_NAME)
        .robot_description(
            file_path=PathJoinSubstitution([FindPackageShare(DESCRIPTION_PACKAGE), *URDF_PATH]),
            mappings=URDF_MAPPINGS,
        )
        .robot_description_semantic(
            file_path=PathJoinSubstitution([FindPackageShare(PACKAGE_NAME), *SRDF_PATH])
        )
        .robot_description_kinematics(
            file_path=PathJoinSubstitution([FindPackageShare(PACKAGE_NAME), "config", "kinematics.yaml"])
        )
        .robot_description_planning(
            file_path=PathJoinSubstitution([FindPackageShare(PACKAGE_NAME), "config", "joint_limits.yaml"])
        )
        .to_moveit_configs()
    )


def generate_launch_description():
    moveit_config = build_moveit_config()

    use_gui = LaunchConfiguration("use_gui")
    use_rviz = LaunchConfiguration("use_rviz")

    joint_state_publisher = Node(
        package="joint_state_publisher",
        executable="joint_state_publisher",
        output="screen",
        condition=UnlessCondition(use_gui),
    )

    joint_state_publisher_gui = Node(
        package="joint_state_publisher_gui",
        executable="joint_state_publisher_gui",
        output="screen",
        condition=IfCondition(use_gui),
    )

    robot_state_publisher = Node(
        package="robot_state_publisher",
        executable="robot_state_publisher",
        output="screen",
        parameters=[moveit_config.robot_description],
    )

    move_group = Node(
        package="moveit_ros_move_group",
        executable="move_group",
        output="screen",
        parameters=[moveit_config.to_dict()],
    )

    rviz_config = LaunchConfiguration("rviz_config")
    rviz = Node(
        package="rviz2",
        executable="rviz2",
        output="screen",
        condition=IfCondition(use_rviz),
        arguments=["-d", rviz_config],
        parameters=[
            moveit_config.robot_description,
            moveit_config.robot_description_semantic,
            moveit_config.robot_description_kinematics,
            moveit_config.robot_description_planning,
        ],
    )

    return LaunchDescription(
        [
            DeclareLaunchArgument("use_gui", default_value="false"),
            DeclareLaunchArgument("use_rviz", default_value="true"),
            DeclareLaunchArgument(
                "rviz_config",
                default_value=PathJoinSubstitution(
                    [FindPackageShare(PACKAGE_NAME), "launch", "moveit.rviz"]
                ),
            ),
            joint_state_publisher,
            joint_state_publisher_gui,
            robot_state_publisher,
            move_group,
            rviz,
        ]
    )
