# Generated by Easy Manipulator Improved ROS 2 conversion.

from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument
from launch.substitutions import IfElseSubstitution, LaunchConfiguration
from launch_ros.actions import Node


def generate_launch_description():
    debug = LaunchConfiguration("debug")
    launch_prefix = IfElseSubstitution(debug, "gdb --ex run --args", "")

    return LaunchDescription(
        [
            DeclareLaunchArgument("debug", default_value="false"),
            Node(
                package="moveit_setup_assistant",
                executable="moveit_setup_assistant",
                name="moveit_setup_assistant",
                output="screen",
                arguments=["--config_pkg=robotiq_3f_moveit_config"],
                prefix=launch_prefix,
            ),
        ]
    )
