# Autogenerated from ROS 1 launch file.
from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, GroupAction
from launch.actions import IncludeLaunchDescription
from launch.conditions import IfCondition, UnlessCondition
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch.substitutions import Command
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node
from launch_ros.actions import PushRosNamespace
from launch_ros.parameter_descriptions import ParameterValue
import os

def generate_launch_description():
    actions = []
    actions.append(DeclareLaunchArgument('planning_plugin', default_value='chomp_interface/CHOMPPlanner'))
    actions.append(DeclareLaunchArgument('start_state_max_bounds_error', default_value='0.1'))
    actions.append(Node(package='rclcpp_components', executable='component_container', name='parameter_loader_1', parameters=[{'planning_plugin': LaunchConfiguration('planning_plugin')}]))
    actions.append(Node(package='rclcpp_components', executable='component_container', name='parameter_loader_2', parameters=[{'start_state_max_bounds_error': LaunchConfiguration('start_state_max_bounds_error')}]))
    actions.append(Node(package='rclcpp_components', executable='component_container', name='parameter_loader_3', parameters=[os.path.join(get_package_share_directory('moveit_resources_fanuc_moveit_config'), 'config/chomp_planning.yaml')]))
    return LaunchDescription(actions)
