# Autogenerated from ROS 1 launch file.
from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, GroupAction
from launch.actions import IncludeLaunchDescription
from launch.conditions import IfCondition, UnlessCondition
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch.substitutions import Command
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node
from launch_ros.actions import PushRosNamespace
from launch_ros.parameter_descriptions import ParameterValue
import os

def generate_launch_description():
    actions = []
    actions.append(DeclareLaunchArgument('db', default_value='false'))
    actions.append(DeclareLaunchArgument('db_path', default_value=os.path.join(get_package_share_directory('moveit_resources_fanuc_moveit_config'), 'default_warehouse_mongo_db')))
    actions.append(DeclareLaunchArgument('debug', default_value='false'))
    actions.append(DeclareLaunchArgument('use_gui', default_value='false'))
    actions.append(DeclareLaunchArgument('gazebo_gui', default_value='true'))
    actions.append(DeclareLaunchArgument('paused', default_value='false'))
    actions.append(DeclareLaunchArgument('urdf_path', default_value=os.path.join(get_package_share_directory('moveit_resources_fanuc_description'), 'urdf/fanuc.urdf')))
    actions.append(IncludeLaunchDescription(PythonLaunchDescriptionSource(os.path.join(get_package_share_directory('moveit_resources_fanuc_moveit_config'), 'launch/gazebo.launch.py')), launch_arguments=dict([('paused', LaunchConfiguration('paused')), ('gazebo_gui', LaunchConfiguration('gazebo_gui')), ('urdf_path', LaunchConfiguration('urdf_path'))]).items()))
    actions.append(IncludeLaunchDescription(PythonLaunchDescriptionSource(os.path.join(get_package_share_directory('moveit_resources_fanuc_moveit_config'), 'launch/planning_context.launch.py')), launch_arguments=dict([('load_robot_description', 'false')]).items()))
    actions.append(Node(package='joint_state_publisher', executable='joint_state_publisher', name='joint_state_publisher', parameters=[{'use_gui': LaunchConfiguration('use_gui')}, {'source_list': '[/joint_states]'}]))
    actions.append(Node(package='robot_state_publisher', executable='robot_state_publisher', name='robot_state_publisher', output='screen', respawn=True))
    actions.append(IncludeLaunchDescription(PythonLaunchDescriptionSource(os.path.join(get_package_share_directory('moveit_resources_fanuc_moveit_config'), 'launch/move_group.launch.py')), launch_arguments=dict([('allow_trajectory_execution', 'true'), ('fake_execution', 'false'), ('info', 'true'), ('debug', LaunchConfiguration('debug'))]).items()))
    actions.append(IncludeLaunchDescription(PythonLaunchDescriptionSource(os.path.join(get_package_share_directory('moveit_resources_fanuc_moveit_config'), 'launch/moveit_rviz.launch.py')), launch_arguments=dict([('rviz_config', os.path.join(get_package_share_directory('moveit_resources_fanuc_moveit_config'), 'launch/moveit.rviz')), ('debug', LaunchConfiguration('debug'))]).items()))
    actions.append(IncludeLaunchDescription(PythonLaunchDescriptionSource(os.path.join(get_package_share_directory('moveit_resources_fanuc_moveit_config'), 'launch/default_warehouse_db.launch.py')), launch_arguments=dict([('moveit_warehouse_database_path', LaunchConfiguration('db_path'))]).items(), condition=IfCondition(LaunchConfiguration('db'))))
    return LaunchDescription(actions)
