# Generated by Easy Manipulator Improved ROS 2 conversion.

from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, IncludeLaunchDescription
from launch.conditions import IfCondition
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch.substitutions import LaunchConfiguration, PathJoinSubstitution
from launch_ros.actions import Node
from launch_ros.substitutions import FindPackageShare


MOVEIT_CONFIG_PACKAGE = "fanuc_moveit_config"


def generate_launch_description():
    db = LaunchConfiguration("db")
    db_path = LaunchConfiguration("db_path")
    use_gui = LaunchConfiguration("use_gui")
    gazebo_gui = LaunchConfiguration("gazebo_gui")
    paused = LaunchConfiguration("paused")
    urdf_path = LaunchConfiguration("urdf_path")

    gazebo = IncludeLaunchDescription(
        PythonLaunchDescriptionSource(
            PathJoinSubstitution(
                [FindPackageShare(MOVEIT_CONFIG_PACKAGE), "launch", "gazebo.launch.py"]
            )
        ),
        launch_arguments={
            "paused": paused,
            "gazebo_gui": gazebo_gui,
            "urdf_path": urdf_path,
        }.items(),
    )

    planning_context = IncludeLaunchDescription(
        PythonLaunchDescriptionSource(
            PathJoinSubstitution(
                [FindPackageShare(MOVEIT_CONFIG_PACKAGE), "launch", "planning_context.launch.py"]
            )
        ),
        launch_arguments={"load_robot_description": "false"}.items(),
    )

    joint_state_publisher = Node(
        package="joint_state_publisher",
        executable="joint_state_publisher",
        output="screen",
        parameters=[
            {
                "use_gui": use_gui,
                "source_list": ["/joint_states"],
            }
        ],
    )

    robot_state_publisher = Node(
        package="robot_state_publisher",
        executable="robot_state_publisher",
        output="screen",
    )

    move_group = IncludeLaunchDescription(
        PythonLaunchDescriptionSource(
            PathJoinSubstitution(
                [FindPackageShare(MOVEIT_CONFIG_PACKAGE), "launch", "move_group.launch.py"]
            )
        )
    )

    rviz = IncludeLaunchDescription(
        PythonLaunchDescriptionSource(
            PathJoinSubstitution(
                [FindPackageShare(MOVEIT_CONFIG_PACKAGE), "launch", "moveit_rviz.launch.py"]
            )
        )
    )

    warehouse = IncludeLaunchDescription(
        PythonLaunchDescriptionSource(
            PathJoinSubstitution(
                [
                    FindPackageShare(MOVEIT_CONFIG_PACKAGE),
                    "launch",
                    "default_warehouse_db.launch.py",
                ]
            )
        ),
        launch_arguments={"moveit_warehouse_database_path": db_path}.items(),
        condition=IfCondition(db),
    )

    return LaunchDescription(
        [
            DeclareLaunchArgument("db", default_value="false"),
            DeclareLaunchArgument(
                "db_path",
                default_value=PathJoinSubstitution(
                    [FindPackageShare(MOVEIT_CONFIG_PACKAGE), "default_warehouse_mongo_db"]
                ),
            ),
            DeclareLaunchArgument("debug", default_value="false"),
            DeclareLaunchArgument("use_gui", default_value="false"),
            DeclareLaunchArgument("gazebo_gui", default_value="true"),
            DeclareLaunchArgument("paused", default_value="false"),
            DeclareLaunchArgument(
                "urdf_path",
                default_value=PathJoinSubstitution(
                    [FindPackageShare("moveit_resources_fanuc_description"), "urdf", "fanuc.urdf"]
                ),
            ),
            gazebo,
            planning_context,
            joint_state_publisher,
            robot_state_publisher,
            move_group,
            rviz,
            warehouse,
        ]
    )
