# Generated by Easy Manipulator Improved ROS 2 conversion.

from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, IncludeLaunchDescription
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch.substitutions import LaunchConfiguration, PathJoinSubstitution
from launch_ros.actions import Node
from launch_ros.substitutions import FindPackageShare


DESCRIPTION_PACKAGE = "moveit_resources_fanuc_description"


def generate_launch_description():
    paused = LaunchConfiguration("paused")
    gazebo_gui = LaunchConfiguration("gazebo_gui")
    urdf_path = LaunchConfiguration("urdf_path")

    gazebo = IncludeLaunchDescription(
        PythonLaunchDescriptionSource(
            PathJoinSubstitution([FindPackageShare("gazebo_ros"), "launch", "gazebo.launch.py"])
        ),
        launch_arguments={
            "world": "worlds/empty.world",
            "gui": gazebo_gui,
            "paused": paused,
        }.items(),
    )

    spawn_entity = Node(
        package="gazebo_ros",
        executable="spawn_entity.py",
        output="screen",
        arguments=["-entity", "robot", "-file", urdf_path, "-x", "0", "-y", "0", "-z", "0"],
    )

    controllers = IncludeLaunchDescription(
        PythonLaunchDescriptionSource(
            PathJoinSubstitution(
                [
                    FindPackageShare("fanuc_moveit_config"),
                    "launch",
                    "ros_controllers.launch.py",
                ]
            )
        )
    )

    return LaunchDescription(
        [
            DeclareLaunchArgument("paused", default_value="false"),
            DeclareLaunchArgument("gazebo_gui", default_value="true"),
            DeclareLaunchArgument(
                "urdf_path",
                default_value=PathJoinSubstitution(
                    [FindPackageShare(DESCRIPTION_PACKAGE), "urdf", "fanuc.urdf"]
                ),
            ),
            gazebo,
            spawn_entity,
            controllers,
        ]
    )
