# Autogenerated from ROS 1 launch file.
from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, GroupAction
from launch.actions import IncludeLaunchDescription
from launch.conditions import IfCondition, UnlessCondition
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch.substitutions import Command
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node
from launch_ros.actions import PushRosNamespace
from launch_ros.parameter_descriptions import ParameterValue
import os

def generate_launch_description():
    actions = []
    actions.append(DeclareLaunchArgument('paused', default_value='false'))
    actions.append(DeclareLaunchArgument('gazebo_gui', default_value='true'))
    actions.append(DeclareLaunchArgument('urdf_path', default_value=os.path.join(get_package_share_directory('moveit_resources_fanuc_description'), 'urdf/fanuc.urdf')))
    actions.append(IncludeLaunchDescription(PythonLaunchDescriptionSource(os.path.join(get_package_share_directory('gazebo_ros'), 'launch/empty_world.launch.py')), launch_arguments=dict([('world_name', ''), ('paused', LaunchConfiguration('paused')), ('gui', LaunchConfiguration('gazebo_gui'))]).items()))
    actions.append(Node(package='rclcpp_components', executable='component_container', name='parameter_loader_1', parameters=[{'robot_description': LaunchConfiguration('urdf_path')}]))
    actions.append(Node(package='gazebo_ros', executable='spawn_model', name='spawn_gazebo_model', output='screen', arguments=['-urdf', '-param', 'robot_description', '-model', 'robot', '-x', '0', '-y', '0', '-z', '0'], respawn=False))
    actions.append(IncludeLaunchDescription(PythonLaunchDescriptionSource(os.path.join(get_package_share_directory('moveit_resources_fanuc_moveit_config'), 'launch/ros_controllers.launch.py'))))
    return LaunchDescription(actions)
