# Generated by Easy Manipulator Improved ROS 2 conversion.

from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument
from launch.conditions import IfCondition, UnlessCondition
from launch.substitutions import Command, LaunchConfiguration, PathJoinSubstitution
from launch_ros.actions import Node
from launch_ros.parameter_descriptions import ParameterValue
from launch_ros.substitutions import FindPackageShare
from launch.substitutions import FindExecutable


MOVEIT_CONFIG_PACKAGE = "fanuc_moveit_config"
DESCRIPTION_PACKAGE = "moveit_resources_fanuc_description"
URDF_FILE = "fanuc.urdf"
SRDF_FILE = "fanuc.srdf"


def generate_robot_description():
    return ParameterValue(
        Command(
            [
                FindExecutable(name="cat"),
                " ",
                PathJoinSubstitution(
                    [FindPackageShare(DESCRIPTION_PACKAGE), "urdf", URDF_FILE]
                ),
            ]
        ),
        value_type=str,
    )


def generate_robot_description_semantic():
    return ParameterValue(
        Command(
            [
                FindExecutable(name="cat"),
                " ",
                PathJoinSubstitution(
                    [FindPackageShare(MOVEIT_CONFIG_PACKAGE), "config", SRDF_FILE]
                ),
            ]
        ),
        value_type=str,
    )


def generate_launch_description():
    rviz_config = LaunchConfiguration("rviz_config")

    robot_description = generate_robot_description()
    robot_description_semantic = generate_robot_description_semantic()

    kinematics_yaml = PathJoinSubstitution(
        [FindPackageShare(MOVEIT_CONFIG_PACKAGE), "config", "kinematics.yaml"]
    )
    joint_limits_yaml = PathJoinSubstitution(
        [FindPackageShare(MOVEIT_CONFIG_PACKAGE), "config", "joint_limits.yaml"]
    )

    rviz_with_config = Node(
        package="rviz2",
        executable="rviz2",
        output="screen",
        condition=IfCondition(rviz_config),
        arguments=["-d", rviz_config],
        parameters=[
            {
                "robot_description": robot_description,
                "robot_description_semantic": robot_description_semantic,
            },
            kinematics_yaml,
            joint_limits_yaml,
        ],
    )

    rviz_without_config = Node(
        package="rviz2",
        executable="rviz2",
        output="screen",
        condition=UnlessCondition(rviz_config),
        parameters=[
            {
                "robot_description": robot_description,
                "robot_description_semantic": robot_description_semantic,
            },
            kinematics_yaml,
            joint_limits_yaml,
        ],
    )

    return LaunchDescription(
        [
            DeclareLaunchArgument("rviz_config", default_value=""),
            rviz_with_config,
            rviz_without_config,
        ]
    )
