# Autogenerated from ROS 1 launch file.
from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, GroupAction
from launch.actions import IncludeLaunchDescription
from launch.conditions import IfCondition, UnlessCondition
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch.substitutions import Command
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node
from launch_ros.actions import PushRosNamespace
from launch_ros.parameter_descriptions import ParameterValue
import os

def generate_launch_description():
    actions = []
    actions.append(DeclareLaunchArgument('load_robot_description', default_value='false'))
    actions.append(DeclareLaunchArgument('robot_description', default_value='robot_description'))
    actions.append(Node(package='rclcpp_components', executable='component_container', name='parameter_loader_1', parameters=[{LaunchConfiguration('robot_description'): os.path.join(get_package_share_directory('moveit_resources_fanuc_description'), 'urdf/fanuc.urdf')}], condition=IfCondition(LaunchConfiguration('load_robot_description'))))
    actions.append(Node(package='rclcpp_components', executable='component_container', name='parameter_loader_2', parameters=[{LaunchConfiguration('robot_description') + '_semantic': os.path.join(get_package_share_directory('moveit_resources_fanuc_moveit_config'), 'config/fanuc.srdf')}]))
    actions.append(GroupAction(actions=[PushRosNamespace(LaunchConfiguration('robot_description') + '_planning'), Node(package='rclcpp_components', executable='component_container', name='parameter_loader_3', parameters=[os.path.join(get_package_share_directory('moveit_resources_fanuc_moveit_config'), 'config/joint_limits.yaml')])]))
    actions.append(GroupAction(actions=[PushRosNamespace(LaunchConfiguration('robot_description') + '_kinematics'), Node(package='rclcpp_components', executable='component_container', name='parameter_loader_4', parameters=[os.path.join(get_package_share_directory('moveit_resources_fanuc_moveit_config'), 'config/kinematics.yaml')])]))
    return LaunchDescription(actions)
