# Autogenerated from ROS 1 launch file.
from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, GroupAction
from launch.actions import IncludeLaunchDescription
from launch.conditions import IfCondition, UnlessCondition
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch.substitutions import Command
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node
from launch_ros.actions import PushRosNamespace
from launch_ros.parameter_descriptions import ParameterValue
import os

def generate_launch_description():
    actions = []
    actions.append(Node(package='rclcpp_components', executable='component_container', name='parameter_loader_1', parameters=[os.path.join(get_package_share_directory('moveit_resources_fanuc_moveit_config'), 'config/ros_controllers.yaml')]))
    actions.append(Node(package='controller_manager', executable='spawner', name='controller_spawner', output='screen', respawn=False))
    return LaunchDescription(actions)
