# Generated by Easy Manipulator Improved ROS 2 conversion.

from launch import LaunchDescription
from launch_ros.actions import Node


def generate_launch_description():
    controller_spawner = Node(
        package="controller_manager",
        executable="spawner",
        output="screen",
        arguments=["joint_state_broadcaster"],
    )

    return LaunchDescription([controller_spawner])
