# Autogenerated from ROS 1 launch file.
from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, GroupAction
from launch.actions import IncludeLaunchDescription
from launch.conditions import IfCondition, UnlessCondition
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch.substitutions import Command
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node
from launch_ros.actions import PushRosNamespace
from launch_ros.parameter_descriptions import ParameterValue
import os

def generate_launch_description():
    actions = []
    actions.append(DeclareLaunchArgument('moveit_warehouse_port', default_value='33829'))
    actions.append(DeclareLaunchArgument('moveit_warehouse_host', default_value='localhost'))
    actions.append(Node(package='rclcpp_components', executable='component_container', name='parameter_loader_1', parameters=[{'warehouse_port': LaunchConfiguration('moveit_warehouse_port')}]))
    actions.append(Node(package='rclcpp_components', executable='component_container', name='parameter_loader_2', parameters=[{'warehouse_host': LaunchConfiguration('moveit_warehouse_host')}]))
    actions.append(Node(package='rclcpp_components', executable='component_container', name='parameter_loader_3', parameters=[{'warehouse_exec': 'mongod'}]))
    actions.append(Node(package='rclcpp_components', executable='component_container', name='parameter_loader_4', parameters=[{'warehouse_plugin': 'warehouse_ros_mongo::MongoDatabaseConnection'}]))
    return LaunchDescription(actions)
