<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>workcell_builder</name>
  <version>0.1.1</version>

  <description>A ROS2 package that provides a GUI for workcell building</description>
  <maintainer email="glenn_tan@artc.a-star.edu.sg">Tan Jing Peng Glenn</maintainer>
  <license>Apache License 2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>rclcpp_components</depend>
  <depend>tf2</depend>
  <depend>tf2_ros</depend>
  <depend>tf2_eigen</depend>
  <depend>tf2_geometry_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>moveit_core</depend>
  <depend>moveit_ros_planning_interface</depend>
  <depend>moveit_visual_tools</depend>
  <depend>pluginlib</depend>
  <depend>ament_index_cpp</depend>
  <depend>yaml-cpp</depend>
  <depend>boost</depend>

  <build_depend>qtbase5-dev</build_depend>
  <build_depend>libqt5svg5-dev</build_depend>
  <build_depend>libqt5opengl5-dev</build_depend>
  <build_depend>qt5-qmake</build_depend>
  <build_depend>qtwebengine5-dev</build_depend>
  <exec_depend>qtbase5-dev</exec_depend>
  <exec_depend>libqt5svg5-dev</exec_depend>
  <exec_depend>libqt5opengl5-dev</exec_depend>
  <exec_depend>qt5-qmake</exec_depend>
  <exec_depend>qtwebengine5-dev</exec_depend>
  <!--test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend-->
  <test_depend>controller_manager_msgs</test_depend>
  <test_depend>launch_testing</test_depend>
  <test_depend>launch_testing_ament_cmake</test_depend>
  <test_depend>launch_testing_ros</test_depend>
  <test_depend>rclpy</test_depend>
  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
