#include "workcell_perception_snapshot.hpp"
#include <boost/filesystem.hpp>
#include <algorithm>
#include <fstream>
#include <sstream>
#include <unordered_map>
#include "workcell_yaml_utils.hpp"
#include "workcell_warning_once.hpp"

namespace fs = boost::filesystem;
namespace workcell_builder {
namespace {
std::array<double,3> a3(const YAML::Node&n){ if(!n||!n.IsSequence()||n.size()<3||!n[0].IsScalar()||!n[1].IsScalar()||!n[2].IsScalar()) return {{0,0,0}}; return {{n[0].as<double>(),n[1].as<double>(),n[2].as<double>()}}; }
}
PerceptionSnapshot parse_detection_snapshot_yaml(const std::string & path){
  PerceptionSnapshot out;
  try {
    const YAML::Node root = YAML::LoadFile(path);
    const YAML::Node s = get_map(root, "detection_snapshot");
    if (!s) return out;
    if (const auto n = get_scalar(s, "schema_version")) out.schema_version = n.as<int>();
    if (const auto n = get_scalar(s, "source")) out.source = n.as<std::string>();
    if (const auto n = get_scalar(s, "runtime_mode")) out.runtime_mode = n.as<std::string>();
    if (const auto n = get_scalar(s, "camera")) out.camera = n.as<std::string>();
    if (const auto n = get_scalar(s, "camera_frame")) out.camera_frame = n.as<std::string>();
    if (const auto n = get_scalar(s, "timestamp_sec")) out.timestamp_sec = n.as<double>();
    if (const auto detections = get_sequence(s, "detections")) for(const auto &d:detections){ if(!d||!d.IsMap()) continue; PerceptionDetection pd; if(const auto n=get_scalar(d,"id")) pd.id=n.as<std::string>(); if(const auto n=get_scalar(d,"class_label")) pd.class_label=n.as<std::string>(); if(const auto n=get_scalar(d,"confidence")) pd.confidence=n.as<double>(); const YAML::Node center=get_sequence(d,"center_px"); if(center&&center.size()>=2&&center[0].IsScalar()&&center[1].IsScalar()){ pd.center_px={{center[0].as<double>(),center[1].as<double>()}}; } const YAML::Node bbox=get_sequence(d,"bbox_px"); if(bbox&&bbox.size()>=4&&bbox[0].IsScalar()&&bbox[1].IsScalar()&&bbox[2].IsScalar()&&bbox[3].IsScalar()){ pd.bbox_px={{bbox[0].as<double>(),bbox[1].as<double>(),bbox[2].as<double>(),bbox[3].as<double>()}}; } pd.estimated_xyz_camera=a3(get_sequence(d,"estimated_xyz_camera")); const YAML::Node world=get_sequence(d,"estimated_xyz_world"); if(world&&world.size()>=3){ pd.estimated_xyz_world=a3(world); pd.has_world_xyz=true; } if(const auto n=get_scalar(d,"zone_hint")) pd.zone_hint=n.as<std::string>(); if(const auto n=get_scalar(d,"tracking_id")) pd.tracking_id=n.as<std::string>(); out.detections.push_back(pd);} 
  } catch (const YAML::Exception &) {
    log_warning_once_per_context_path_reason("perception_snapshot_reader", path, "scene YAML parse failed");
    return out;
  } catch (const std::exception &) {
    log_warning_once_per_context_path_reason("perception_snapshot_reader", path, "scene YAML parse failed");
    return out;
  }
  return out;
}
PerceptionSnapshot parse_detection_snapshot_json(const std::string & path){ return parse_detection_snapshot_yaml(path); }
std::string serialize_detection_snapshot_yaml(const PerceptionSnapshot & s){ YAML::Emitter out; out<<YAML::BeginMap<<YAML::Key<<"detection_snapshot"<<YAML::Value<<YAML::BeginMap<<YAML::Key<<"schema_version"<<YAML::Value<<s.schema_version<<YAML::Key<<"source"<<YAML::Value<<s.source<<YAML::Key<<"runtime_mode"<<YAML::Value<<s.runtime_mode<<YAML::Key<<"camera"<<YAML::Value<<s.camera<<YAML::Key<<"camera_frame"<<YAML::Value<<s.camera_frame<<YAML::Key<<"timestamp_sec"<<YAML::Value<<s.timestamp_sec<<YAML::Key<<"detections"<<YAML::Value<<YAML::BeginSeq; for(const auto&d:s.detections){ out<<YAML::BeginMap<<YAML::Key<<"id"<<YAML::Value<<d.id<<YAML::Key<<"class_label"<<YAML::Value<<d.class_label<<YAML::Key<<"confidence"<<YAML::Value<<d.confidence<<YAML::Key<<"center_px"<<YAML::Value<<YAML::Flow<<std::vector<double>{d.center_px[0],d.center_px[1]}<<YAML::Key<<"bbox_px"<<YAML::Value<<YAML::Flow<<std::vector<double>{d.bbox_px[0],d.bbox_px[1],d.bbox_px[2],d.bbox_px[3]}<<YAML::Key<<"estimated_xyz_camera"<<YAML::Value<<YAML::Flow<<std::vector<double>{d.estimated_xyz_camera[0],d.estimated_xyz_camera[1],d.estimated_xyz_camera[2]}; if(d.has_world_xyz) out<<YAML::Key<<"estimated_xyz_world"<<YAML::Value<<YAML::Flow<<std::vector<double>{d.estimated_xyz_world[0],d.estimated_xyz_world[1],d.estimated_xyz_world[2]}; out<<YAML::Key<<"zone_hint"<<YAML::Value<<d.zone_hint<<YAML::Key<<"tracking_id"<<YAML::Value<<d.tracking_id<<YAML::EndMap;} out<<YAML::EndSeq<<YAML::EndMap<<YAML::EndMap; return out.c_str(); }
std::string serialize_detection_snapshot_json(const PerceptionSnapshot & s){ std::ostringstream ss; ss<<"{\n  \"detection_snapshot\": {\n    \"schema_version\": "<<s.schema_version<<",\n    \"source\": \""<<s.source<<"\",\n    \"runtime_mode\": \""<<s.runtime_mode<<"\",\n    \"camera\": \""<<s.camera<<"\",\n    \"camera_frame\": \""<<s.camera_frame<<"\",\n    \"timestamp_sec\": "<<s.timestamp_sec<<",\n    \"detections\": []\n  }\n}"; return ss.str(); }
std::vector<std::string> validate_detection_snapshot(const PerceptionSnapshot & s,const std::vector<WorkcellCamera>&cams,const std::vector<WorkZone>&zones,double min_conf){ std::vector<std::string> out; bool cam=false; for(const auto&c:cams) if(c.name==s.camera) cam=true; if(!cam) out.push_back("ERROR: snapshot camera does not match any configured camera"); std::unordered_map<std::string,WorkZone> zn; for(const auto&z:zones) zn[z.name]=z; for(const auto&d:s.detections){ if(d.bbox_px[2]<=0||d.bbox_px[3]<=0) out.push_back("ERROR: malformed bbox/center/xyz values"); if(!d.zone_hint.empty()&& !zn.count(d.zone_hint)) out.push_back("ERROR: detection uses zone_hint that does not exist"); if(!d.has_world_xyz) out.push_back("WARN: detection has no world coordinate"); if(d.confidence<min_conf) out.push_back("WARN: confidence below configurable threshold"); } out.push_back("INFO: adapter_metadata_only"); return out; }
std::vector<DetectionAdapterResult> map_detection_to_conveyor_preview(const PerceptionSnapshot & s,const std::vector<WorkcellCamera>&,const std::vector<WorkZone>&zones,const std::vector<ConveyorFlow>&flows){ std::unordered_map<std::string,WorkZone> zn; for(const auto&z:zones) zn[z.name]=z; std::unordered_map<std::string,ConveyorFlow> by_det; for(const auto&f:flows) by_det[f.detection_zone]=f; std::vector<DetectionAdapterResult> out; for(const auto&d:s.detections){ DetectionAdapterResult r; r.detection_id=d.id; r.class_label=d.class_label; r.camera=s.camera; r.runtime_mode="preview_only"; std::string zone=d.zone_hint; if(zone.empty() && d.has_world_xyz){ for(const auto&z:zones){ if(z.type!="camera_detection"||z.center_xyz.size()<3||z.size_xyz.size()<3) continue; if(std::abs(d.estimated_xyz_world[0]-z.center_xyz[0])<=z.size_xyz[0]/2.0 && std::abs(d.estimated_xyz_world[1]-z.center_xyz[1])<=z.size_xyz[1]/2.0 && std::abs(d.estimated_xyz_world[2]-z.center_xyz[2])<=z.size_xyz[2]/2.0){ zone=z.name; break; } } }
 r.detection_zone=zone; if(zone.empty()) r.warnings.push_back("WARN: detection not inside any detection zone"); if(by_det.count(zone)){ auto f=by_det[zone]; r.conveyor_flow=f.name; r.pick_zone=f.pick_zone; r.distance_to_pick_m=compute_conveyor_flow_distance(f); r.time_to_pick_s=compute_time_to_pick(r.distance_to_pick_m,f.speed_mps); r.pick_ready=r.time_to_pick_s<0.5; } else if(!zone.empty()) r.errors.push_back("ERROR: detection requires conveyor preview but conveyor_flow missing"); out.push_back(r);} return out; }
PerceptionSnapshot generate_sample_epd_detection_snapshot(const std::string & camera_name, const std::string & camera_frame){ PerceptionSnapshot s; s.camera=camera_name; s.camera_frame=camera_frame; PerceptionDetection d; d.id="det_001"; d.class_label="box"; d.confidence=0.92; d.center_px={{320,180}}; d.bbox_px={{280,140,80,70}}; d.estimated_xyz_camera={{0.05,0.02,0.85}}; d.estimated_xyz_world={{0.60,0.0,0.80}}; d.has_world_xyz=true; d.zone_hint="detection_zone_1"; d.tracking_id="track_001"; s.detections.push_back(d); return s; }
void write_detection_mapping_artifacts(const std::string & out_dir, const PerceptionSnapshot & snapshot, const std::vector<DetectionAdapterResult> & mapped){ fs::create_directories(out_dir); std::ofstream(out_dir+"/perception_detection_snapshot.yaml")<<serialize_detection_snapshot_yaml(snapshot); YAML::Emitter y; y<<YAML::BeginMap<<YAML::Key<<"workcell_detection_mapping"<<YAML::Value<<YAML::BeginSeq; std::ostringstream js; js<<"{\n  \"workcell_detection_mapping\": [\n"; for(size_t i=0;i<mapped.size();++i){ const auto&r=mapped[i]; y<<YAML::BeginMap<<YAML::Key<<"detection_id"<<YAML::Value<<r.detection_id<<YAML::Key<<"class_label"<<YAML::Value<<r.class_label<<YAML::Key<<"camera"<<YAML::Value<<r.camera<<YAML::Key<<"detection_zone"<<YAML::Value<<r.detection_zone<<YAML::Key<<"conveyor_flow"<<YAML::Value<<r.conveyor_flow<<YAML::Key<<"pick_zone"<<YAML::Value<<r.pick_zone<<YAML::Key<<"distance_to_pick_m"<<YAML::Value<<r.distance_to_pick_m<<YAML::Key<<"time_to_pick_s"<<YAML::Value<<r.time_to_pick_s<<YAML::Key<<"state"<<YAML::Value<<r.state<<YAML::Key<<"pick_ready"<<YAML::Value<<r.pick_ready<<YAML::Key<<"runtime_mode"<<YAML::Value<<r.runtime_mode<<YAML::Key<<"robot_motion_commanded"<<YAML::Value<<false<<YAML::EndMap; js<<"    {\"detection_id\":\""<<r.detection_id<<"\",\"runtime_mode\":\"preview_only\",\"robot_motion_commanded\":false}"<<(i+1<mapped.size()?",":"")<<"\n"; } y<<YAML::EndSeq<<YAML::EndMap; js<<"  ]\n}"; std::ofstream(out_dir+"/perception_detection_mapping.yaml")<<y.c_str(); std::ofstream(out_dir+"/perception_detection_mapping.json")<<js.str(); }
}
