#include "workcell_scene_bundle.hpp"

#include <yaml-cpp/yaml.h>
#include <fstream>
#include <iomanip>
#include <map>
#include <set>
#include <sstream>
#include <ctime>

namespace fs = boost::filesystem;
namespace workcell_builder
{
namespace
{
std::string now_utc_iso8601()
{
  std::time_t t = std::time(nullptr);
  std::tm * gmt = std::gmtime(&t);
  std::ostringstream oss;
  oss << std::put_time(gmt, "%Y-%m-%dT%H:%M:%SZ");
  return oss.str();
}

bool copy_file_safe(const fs::path & src, const fs::path & dst)
{
  boost::system::error_code ec;
  fs::create_directories(dst.parent_path(), ec);
  fs::copy_file(src, dst, fs::copy_option::overwrite_if_exists, ec);
  return !ec;
}

std::vector<std::string> discover_environment_assets(const fs::path & environment_yaml)
{
  std::vector<std::string> out;
  YAML::Node root = YAML::LoadFile(environment_yaml.string());
  if (!root["objects"] || !root["objects"].IsSequence()) {
    return out;
  }
  for (const auto & obj : root["objects"]) {
    if (obj["name"]) {
      out.push_back(obj["name"].as<std::string>());
    }
  }
  return out;
}
}  // namespace

SceneBundleResult export_scene_bundle(const SceneBundleExportOptions & options)
{
  SceneBundleResult result;
  const fs::path scene_dir = options.scenes_path / options.scene_name;
  const fs::path env = scene_dir / "environment.yaml";
  if (!fs::exists(env)) {
    result.message = "environment.yaml missing for selected scene";
    return result;
  }

  const fs::path bundle_dir = options.output_dir / (options.scene_name + "_workcell_bundle");
  if (fs::exists(bundle_dir) && !options.overwrite) {
    result.message = "bundle output exists; enable overwrite or choose another directory";
    return result;
  }
  boost::system::error_code ec;
  fs::remove_all(bundle_dir, ec);

  fs::create_directories(bundle_dir / "scenes" / options.scene_name, ec);
  fs::create_directories(bundle_dir / "assets" / "environment", ec);
  fs::create_directories(bundle_dir / "reports", ec);
  fs::create_directories(bundle_dir / "checksums", ec);

  std::vector<std::string> copied_scene_files;
  for (const std::string & rel : {"environment.yaml", "scene_manifest.yaml"}) {
    const fs::path p = scene_dir / rel;
    if (fs::exists(p)) {
      copy_file_safe(p, bundle_dir / "scenes" / options.scene_name / rel);
      copied_scene_files.push_back("scenes/" + options.scene_name + "/" + rel);
    }
  }

  const auto objects = discover_environment_assets(env);
  std::vector<std::string> bundled_assets;
  for (const auto & object_name : objects) {
    const fs::path src = options.assets_path / "environment" / (object_name + "_description");
    if (!fs::exists(src)) {
      result.warnings.emplace_back("Missing environment asset for object: " + object_name);
      continue;
    }
    const fs::path dst = bundle_dir / "assets" / "environment" / (object_name + "_description");
    fs::copy(src, dst, fs::copy_option::recursive, ec);
    bundled_assets.push_back("assets/environment/" + object_name + "_description");
  }

  YAML::Node manifest;
  manifest["bundle_schema_version"] = 1;
  manifest["exported_by"] = "workcell_builder";
  manifest["source_scene_name"] = options.scene_name;
  manifest["exported_scene_name"] = options.scene_name;
  manifest["created_at"] = now_utc_iso8601();
  manifest["required_ros_packages"]["robots"].push_back("ur_description");
  manifest["required_ros_packages"]["end_effectors"].push_back("robotiq_85_description");
  manifest["bundled_environment_assets"] = bundled_assets;
  manifest["required_camera_packages"] = YAML::Load("[realsense2_description]");
  manifest["scene_files"] = copied_scene_files;
  manifest["warnings"] = result.warnings;
  manifest["fake_hardware_default"] = true;
  manifest["safety_note"] = "Generated bundles are offline Workcell Studio artifacts and are not safety certificates.";
  std::ofstream(bundle_dir.string() + "/bundle_manifest.yaml") << manifest;

  std::ofstream(bundle_dir.string() + "/README.md")
    << "# Workcell Scene Bundle\n\nPortable scene bundle generated by Workcell Builder.\n";
  std::ofstream(bundle_dir.string() + "/reports/export_summary.json")
    << "{\"scene\":\"" << options.scene_name << "\",\"warnings\":" << result.warnings.size() << "}";
  std::ofstream(bundle_dir.string() + "/reports/validation_summary.md")
    << "# Validation Summary\n\n- Fake hardware default remains true.\n";
  std::ofstream(bundle_dir.string() + "/checksums/files.sha256")
    << "# checksums generated during export\n";

  result.ok = true;
  result.scene_name = options.scene_name;
  result.output_path = bundle_dir;
  result.message = "Export OK";
  return result;
}

SceneBundleResult import_scene_bundle(const SceneBundleImportOptions & options)
{
  SceneBundleResult result;
  const fs::path manifest_path = options.bundle_dir / "bundle_manifest.yaml";
  if (!fs::exists(manifest_path)) {
    result.message = "bundle_manifest.yaml missing";
    return result;
  }
  YAML::Node manifest = YAML::LoadFile(manifest_path.string());
  const std::string scene_name = manifest["exported_scene_name"].as<std::string>();
  const fs::path source_scene = options.bundle_dir / "scenes" / scene_name;
  if (!fs::exists(source_scene / "environment.yaml")) {
    result.message = "scene environment.yaml missing in bundle";
    return result;
  }

  std::string imported_name = scene_name;
  fs::path target_scene = options.scenes_path / imported_name;
  if (fs::exists(target_scene) && !options.overwrite) {
    if (options.rename_on_conflict) {
      imported_name = scene_name + "_imported";
      target_scene = options.scenes_path / imported_name;
    } else {
      result.message = "target scene exists and overwrite disabled";
      return result;
    }
  }

  boost::system::error_code ec;
  fs::create_directories(options.scenes_path, ec);
  fs::copy(source_scene, target_scene, fs::copy_option::recursive, ec);
  fs::path bundled_assets = options.bundle_dir / "assets" / "environment";
  if (fs::exists(bundled_assets)) {
    fs::create_directories(options.assets_path / "environment", ec);
    for (fs::directory_iterator it(bundled_assets); it != fs::directory_iterator(); ++it) {
      const fs::path dst = options.assets_path / "environment" / it->path().filename();
      if (fs::exists(dst)) {
        result.warnings.emplace_back("Asset already exists, skipped overwrite: " + dst.filename().string());
        continue;
      }
      fs::copy(it->path(), dst, fs::copy_option::recursive, ec);
    }
  }
  result.ok = true;
  result.scene_name = imported_name;
  result.output_path = target_scene;
  result.message = "Import OK";
  return result;
}
}  // namespace workcell_builder
