#include "workcell_zone_model.hpp"
#include <algorithm>
#include <sstream>
#include <set>
namespace workcell_builder {
WorkZone default_detection_zone_for_camera(const std::string & camera_name){ WorkZone z; z.name="detection_zone_1"; z.type="camera_detection"; z.linked_camera=camera_name; z.purpose="Camera detects objects here"; return z; }
WorkZone default_pick_zone_for_robot(const std::string & robot_name){ WorkZone z; z.name="pick_zone_1"; z.type="robot_pick"; z.linked_robot=robot_name; z.purpose="Robot may pick objects here"; return z; }
WorkZone default_place_zone(const std::string & destination){ WorkZone z; z.name="place_zone_1"; z.type="robot_place"; z.destination=destination; z.purpose="Robot places objects here"; return z; }
void serialize_work_zones_to_yaml(YAML::Emitter *out, const std::vector<WorkZone>& zones, const std::vector<ConveyorFlow>& flows){ *out << YAML::Key << "work_zones" << YAML::Value << YAML::BeginSeq; for (const auto &z: zones){ *out<<YAML::BeginMap<<YAML::Key<<"name"<<YAML::Value<<z.name<<YAML::Key<<"type"<<YAML::Value<<z.type<<YAML::Key<<"parent_frame"<<YAML::Value<<z.parent_frame<<YAML::Key<<"center_xyz"<<YAML::Value<<YAML::Flow<<z.center_xyz<<YAML::Key<<"size_xyz"<<YAML::Value<<YAML::Flow<<z.size_xyz<<YAML::Key<<"rpy"<<YAML::Value<<YAML::Flow<<z.rpy; if(!z.linked_camera.empty()) *out<<YAML::Key<<"linked_camera"<<YAML::Value<<z.linked_camera; if(!z.linked_robot.empty()) *out<<YAML::Key<<"linked_robot"<<YAML::Value<<z.linked_robot; if(!z.destination.empty()) *out<<YAML::Key<<"destination"<<YAML::Value<<z.destination; *out<<YAML::Key<<"purpose"<<YAML::Value<<z.purpose<<YAML::Key<<"runtime_mode"<<YAML::Value<<z.runtime_mode<<YAML::EndMap; } *out<<YAML::EndSeq;
*out << YAML::Key << "conveyor_flows" << YAML::Value << YAML::BeginSeq; for(const auto&f:flows){*out<<YAML::BeginMap<<YAML::Key<<"name"<<YAML::Value<<f.name<<YAML::Key<<"parent_frame"<<YAML::Value<<f.parent_frame<<YAML::Key<<"start_xyz"<<YAML::Value<<YAML::Flow<<f.start_xyz<<YAML::Key<<"end_xyz"<<YAML::Value<<YAML::Flow<<f.end_xyz<<YAML::Key<<"direction_xyz"<<YAML::Value<<YAML::Flow<<f.direction_xyz<<YAML::Key<<"speed_mps"<<YAML::Value<<f.speed_mps<<YAML::Key<<"detection_zone"<<YAML::Value<<f.detection_zone<<YAML::Key<<"pick_zone"<<YAML::Value<<f.pick_zone<<YAML::Key<<"runtime_mode"<<YAML::Value<<f.runtime_mode<<YAML::EndMap;} *out<<YAML::EndSeq; }
void parse_work_zones_from_yaml(const YAML::Node &root, std::vector<WorkZone>* zones, std::vector<ConveyorFlow>* flows){ zones->clear(); flows->clear(); if(root["work_zones"]) for(const auto&n:root["work_zones"]){ WorkZone z; if(n["name"])z.name=n["name"].as<std::string>(); if(n["type"])z.type=n["type"].as<std::string>(); if(n["linked_camera"])z.linked_camera=n["linked_camera"].as<std::string>(); if(n["linked_robot"])z.linked_robot=n["linked_robot"].as<std::string>(); if(n["destination"])z.destination=n["destination"].as<std::string>(); if(n["purpose"])z.purpose=n["purpose"].as<std::string>(); if(n["runtime_mode"])z.runtime_mode=n["runtime_mode"].as<std::string>(); zones->push_back(z);} if(root["conveyor_flows"]) for(const auto&n:root["conveyor_flows"]){ ConveyorFlow f; if(n["name"])f.name=n["name"].as<std::string>(); if(n["detection_zone"])f.detection_zone=n["detection_zone"].as<std::string>(); if(n["pick_zone"])f.pick_zone=n["pick_zone"].as<std::string>(); if(n["runtime_mode"])f.runtime_mode=n["runtime_mode"].as<std::string>(); flows->push_back(f);} }
WorkZoneValidationResult validate_work_zones(const std::vector<WorkZone>& zones, const std::vector<ConveyorFlow>& flows, const std::vector<std::string>& cameras, const std::vector<std::string>& robots){ WorkZoneValidationResult r; std::set<std::string> zn; bool hasD=false,hasP=false,hasL=false; for(const auto&z:zones){ zn.insert(z.name); if(z.type=="camera_detection"){hasD=true; if(!z.linked_camera.empty() && std::find(cameras.begin(),cameras.end(),z.linked_camera)==cameras.end()) r.errors.push_back("Detection zone linked camera missing: "+z.linked_camera);} if(z.type=="robot_pick"){hasP=true; if(z.linked_robot.empty()||std::find(robots.begin(),robots.end(),z.linked_robot)==robots.end()) r.warnings.push_back("Pick zone linked robot missing");} if(z.type=="robot_place") hasL=true; if(z.runtime_mode=="metadata_only") r.infos.push_back("runtime_mode metadata_only"); }
if(!hasD) r.warnings.push_back("Detection zone configured: WARN"); if(!hasP) r.warnings.push_back("Pick zone configured: WARN"); if(!hasL) r.warnings.push_back("Place zone configured: WARN");
for(const auto&f:flows){ if(f.detection_zone.empty() || !zn.count(f.detection_zone)) r.errors.push_back("Conveyor flow missing detection zone"); if(f.pick_zone.empty() || !zn.count(f.pick_zone)) r.errors.push_back("Conveyor flow missing pick zone"); r.infos.push_back("Conveyor flow configured: INFO"); }
r.infos.push_back("Work zones are metadata/preview only, not safety-certified."); r.ok=r.errors.empty(); return r; }
std::string generate_zone_preview_markers_or_geometry(const WorkZone & z){ std::ostringstream ss; ss<<"<box name='"<<z.name<<"' type='"<<z.type<<"' runtime='"<<z.runtime_mode<<"'/>"; return ss.str(); }
std::string generate_conveyor_flow_preview_arrow(const ConveyorFlow & f){ return "<arrow name='"+f.name+"' from='"+f.detection_zone+"' to='"+f.pick_zone+"' runtime='"+f.runtime_mode+"'/>"; }
}
