#include "workcell_studio_template_instantiator.hpp"

#include <algorithm>
#include <cctype>
#include <fstream>
#include <algorithm>
#include <sstream>

#include "file_functions.h"
#include "include/asset_discovery_helper.h"

namespace fs = boost::filesystem;
namespace workcell_builder {
namespace {

std::string normalize_asset_id(const std::string & raw)
{
  std::string out;
  out.reserve(raw.size());
  for (const char c : raw) {
    if (std::isalnum(static_cast<unsigned char>(c))) {
      out.push_back(static_cast<char>(std::tolower(static_cast<unsigned char>(c))));
    }
  }
  return out;
}

bool contains_token(const std::string & haystack, const std::string & needle)
{
  return !needle.empty() && haystack.find(needle) != std::string::npos;
}

std::vector<std::string> alias_tokens_for_id(const std::string & raw_id)
{
  const std::string norm = normalize_asset_id(raw_id);
  std::vector<std::string> tokens;
  if (!norm.empty()) tokens.push_back(norm);
  if (contains_token(norm, "ur5")) {
    tokens.push_back("ur5");
    tokens.push_back("universalrobotur5");
    tokens.push_back("universalrobot");
  }
  if (contains_token(norm, "ur10")) tokens.push_back("ur10");
  if (contains_token(norm, "ur3")) tokens.push_back("ur3");
  if (contains_token(norm, "robotiq") || contains_token(norm, "2f85") || contains_token(norm, "2f")) {
    tokens.push_back("robotiq");
    tokens.push_back("2f85");
  }
  if (contains_token(norm, "airpick") || contains_token(norm, "suction") || contains_token(norm, "vacuum")) {
    tokens.push_back("airpick");
    tokens.push_back("suction");
    tokens.push_back("vacuum");
  }
  std::sort(tokens.begin(), tokens.end());
  tokens.erase(std::unique(tokens.begin(), tokens.end()), tokens.end());
  return tokens;
}

const AssetCandidate * map_selected_to_discovered(
  const std::string & selected_id, const std::vector<AssetCandidate> & candidates)
{
  const auto tokens = alias_tokens_for_id(selected_id);
  for (const auto & candidate : candidates) {
    const std::string key = normalize_asset_id(
      candidate.label + " " + candidate.description_package + " " + candidate.moveit_config_package);
    for (const auto & token : tokens) {
      if (contains_token(key, token)) {
        return &candidate;
      }
    }
  }
  return nullptr;
}

std::string sanitize(const std::string & raw)
{
  std::string out;
  for (const char c : raw) {
    if (std::isalnum(static_cast<unsigned char>(c)) || c == '_' || c == '-') out.push_back(static_cast<char>(std::tolower(static_cast<unsigned char>(c))));
    else if (std::isspace(static_cast<unsigned char>(c))) out.push_back('_');
  }
  return out.empty() ? "new_scene" : out;
}

void write_file(const fs::path & path, const std::string & text, WorkcellStudioTemplateInstantiationResult & r)
{
  fs::create_directories(path.parent_path());
  std::ofstream out(path.string());
  out << text;
  if (out.good()) r.created_files.push_back(path.string());
  else r.blockers.push_back("failed writing: " + path.string());
}

std::string generated_scene_xacro(const std::string & scene_name, const std::string & robot_id, const std::string & end_effector_id)
{
  return std::string(
    "<?xml version=\"1.0\"?>\n"
    "<robot xmlns:xacro=\"http://www.ros.org/wiki/xacro\" name=\"") + scene_name + "\">\n"
    "  <!-- Generated by Workcell Studio: minimal RViz truth preview scene -->\n"
    "  <link name=\"world\"/>\n"
    "\n"
    "  <!-- robot_visual_placeholder_due_to_missing_robot_xacro -->\n"
    "  <link name=\"robot_visual_placeholder_due_to_missing_robot_xacro\">\n"
    "    <visual><geometry><box size=\"0.30 0.20 0.50\"/></geometry><material name=\"blue\"><color rgba=\"0.2 0.4 0.9 1.0\"/></material></visual>\n"
    "  </link>\n"
    "  <joint name=\"world_to_robot_visual_placeholder\" type=\"fixed\">\n"
    "    <parent link=\"world\"/>\n"
    "    <child link=\"robot_visual_placeholder_due_to_missing_robot_xacro\"/>\n"
    "    <origin xyz=\"0 0 0\" rpy=\"0 0 0\"/>\n"
    "  </joint>\n"
    "\n"
    "  <!-- selected_robot_metadata: " + robot_id + " -->\n"
    "  <!-- selected_end_effector_metadata: " + end_effector_id + " -->\n"
    "  <!-- missing end-effector xacro -> placeholder visual only -->\n"
    "\n"
    "  <link name=\"support_surface\">\n"
    "    <visual><geometry><box size=\"1.20 0.80 0.04\"/></geometry><material name=\"gray\"><color rgba=\"0.5 0.5 0.5 1.0\"/></material></visual>\n"
    "  </link>\n"
    "  <joint name=\"world_to_support_surface\" type=\"fixed\">\n"
    "    <parent link=\"world\"/>\n"
    "    <child link=\"support_surface\"/>\n"
    "    <origin xyz=\"0.6 0 0.4\" rpy=\"0 0 0\"/>\n"
    "  </joint>\n"
    "</robot>\n";
}



std::string to_json_string_array(const std::vector<std::string> & values)
{
  std::ostringstream out;
  out << "[";
  for (std::size_t i = 0; i < values.size(); ++i) {
    if (i != 0) out << ", ";
    out << "\"" << values[i] << "\"";
  }
  out << "]";
  return out.str();
}

std::string generated_demo_launch()
{
  return
    "from launch import LaunchDescription\n"
    "from launch.actions import DeclareLaunchArgument\n"
    "from launch.conditions import IfCondition\n"
    "from launch.substitutions import Command, LaunchConfiguration, PathJoinSubstitution\n"
    "from launch_ros.actions import Node\n"
    "from launch_ros.substitutions import FindPackageShare\n\n"
    "\n"
    "def generate_launch_description():\n"
    "    use_fake_hardware = LaunchConfiguration('use_fake_hardware')\n"
    "    launch_rviz = LaunchConfiguration('launch_rviz')\n"
    "    urdf_xacro = PathJoinSubstitution([FindPackageShare(LaunchConfiguration('scene_pkg')), 'urdf', 'scene.urdf.xacro'])\n"
    "    robot_description = {'robot_description': Command(['xacro ', urdf_xacro, ' use_fake_hardware:=', use_fake_hardware])}\n"
    "    rsp = Node(package='robot_state_publisher', executable='robot_state_publisher', parameters=[robot_description])\n"
    "    rviz = Node(package='rviz2', executable='rviz2', condition=IfCondition(launch_rviz), arguments=['-d', PathJoinSubstitution([FindPackageShare(LaunchConfiguration('scene_pkg')), 'launch', 'demo.rviz'])], parameters=[robot_description])\n"
    "    return LaunchDescription([\n"
    "        DeclareLaunchArgument('scene_pkg', default_value='scene_name'),\n"
    "        DeclareLaunchArgument('use_fake_hardware', default_value='true'),\n"
    "        DeclareLaunchArgument('launch_rviz', default_value='true'),\n"
    "        rsp,\n"
    "        rviz,\n"
    "    ])\n";
}

}

WorkcellStudioTemplateInstantiationResult instantiate_workcell_studio_template(const WorkcellStudioTemplateInstantiationRequest & request)
{
  WorkcellStudioTemplateInstantiationResult r;
  const std::string scene_name = sanitize(request.scene_name);
  if (request.template_id.empty() || request.robot_id.empty() || request.end_effector_id.empty()) {
    r.blockers.push_back("template/robot/end_effector must be selected");
    return r;
  }

  fs::path scene_dir = request.scene_root / scene_name;
  int suffix = 2;
  while (fs::exists(scene_dir)) scene_dir = request.scene_root / (scene_name + "_" + std::to_string(suffix++));
  if (scene_dir.filename().string() != scene_name) r.warnings.push_back("scene existed; created suffixed scene: " + scene_dir.filename().string());
  r.scene_dir = scene_dir;

  generate_package_xml(scene_dir, scene_dir.filename().string(), 0, "humble");
  generate_cmakelists(scene_dir, scene_dir.filename().string(), 0, "humble");
  r.created_files.push_back((scene_dir / "package.xml").string());
  r.created_files.push_back((scene_dir / "CMakeLists.txt").string());

  const std::string workspace_root = request.scene_root.parent_path().parent_path().string();
  const std::string repo_root = request.scene_root.parent_path().string();
  const AssetDiscoveryReport discovery = discover_workcell_assets(workspace_root, repo_root);
  const AssetCandidate * robot_entry = map_selected_to_discovered(request.robot_id, discovery.robots);
  const AssetCandidate * tool_entry = map_selected_to_discovered(request.end_effector_id, discovery.end_effectors);

  if (!robot_entry) {
    r.warnings.push_back(
      "Selected robot id '" + request.robot_id +
      "' could not be mapped to discovered robot assets (case/alias normalized).");
    r.warnings.push_back(
      "Next action: open Asset Picker, select a discovered robot package, then regenerate scene package.");
  }
  if (!tool_entry) {
    r.warnings.push_back(
      "Selected tool id '" + request.end_effector_id +
      "' could not be mapped to discovered end-effector assets (case/alias normalized).");
    r.warnings.push_back(
      "Next action: open Asset Picker, select a discovered end-effector package, then regenerate scene package.");
  }

  const std::string resolved_robot_model = robot_entry ? robot_entry->label : request.robot_id;
  const std::string resolved_tool_model = tool_entry ? tool_entry->label : request.end_effector_id;
  const std::string resolved_tool_type = tool_entry ? tool_entry->inferred_type : "unknown";
  const std::string normalized_tool = normalize_asset_id(request.end_effector_id);
  const bool suction =
    resolved_tool_type == "suction" || contains_token(normalized_tool, "suction") ||
    contains_token(normalized_tool, "airpick");
  const std::string normalized_robot = normalize_asset_id(request.robot_id);
  const bool preview_only = !(contains_token(normalized_robot, "ur5") || (robot_entry && contains_token(normalize_asset_id(robot_entry->label), "ur5")));
  const std::string grasp = suction ? "suction_top" : "finger_top";
  const std::string task_type = request.template_id.find("inspection") != std::string::npos ? "inspection_preview" : "pick_place";

  write_file(scene_dir / "environment.yaml",
    "robot:\n  name: " + request.robot_id + "\nend_effector:\n  name: " + request.end_effector_id +
    "\n  mount_rpy: \"-1.5708 -1.5708 0\"\n"
    "workcell_studio:\n"
    "  robot:\n"
    "    family: unknown\n"
    "    model: " + resolved_robot_model + "\n"
    "    base: base_link\n"
    "    tip: tool0\n"
    "    planning_group: manipulator\n"
    "    readiness: PREVIEW_ONLY\n"
    "  tool:\n"
    "    family: unknown\n"
    "    model: " + resolved_tool_model + "\n"
    "    attach: tool0\n"
    "    tcp: tcp_link\n"
    "    type: " + resolved_tool_type + "\n"
    "    mount_pose:\n"
    "      xyz: [0.0, 0.0, 0.0]\n"
    "      rpy: [-1.5708, -1.5708, 0.0]\n"
    "    readiness: PREVIEW_ONLY\n"
    "  frames:\n"
    "    robot_base_link: base_link\n"
    "    robot_tip_link: tool0\n"
    "  environment_objects: []\n"
    "  perception:\n"
    "    mode: preview_only\n"
    "    selected_topics: {}\n"
    "    profile_metadata: {}\n"
    "  pick_zone:\n"
    "    source: default_from_environment\n"
    "  place_zone:\n"
    "    target: default_from_environment\n"
    "  task_intent:\n"
    "    task_family: " + task_type + "\n"
    "    readiness: " + std::string(preview_only ? "PREVIEW_ONLY" : "READY") + "\n"
    "  warnings:\n"
    "    - fake_hardware default true\n"
    "    - real robot locked\n"
    "    - no runtime motion commands\n"
    "task:\n  type: " + task_type + "\n  preview_only: " + std::string(preview_only ? "true" : "false") +
    "\nsafety:\n  preview_only: false\n  use_fake_hardware: true\n  allow_simulated_motion: true\n  allow_moveit_execution: true\n  allow_rviz_motion: true\n  allow_real_hardware_motion: false\n  real_robot_locked: true\n"
    "layout:\n  preset: " + request.layout_preset_id + "\n  include_camera: " + std::string(request.include_camera ? "true" : "false") + "\n  include_conveyor: " + std::string(request.include_conveyor ? "true" : "false") + "\n",
    r);
  write_file(scene_dir / "scene_manifest.yaml", "schema: workcell_scene_manifest/v1\nscene_name: " + scene_dir.filename().string() + "\ntemplate_id: " + request.template_id + "\n", r);
  write_file(scene_dir / "config" / "task_recipe.yaml", "task:\n  type: " + task_type + "\n  grasp_strategy: " + grasp + "\n", r);
  write_file(scene_dir / "config" / "workcell_builder_task_intent.yaml",
    "schema: workcell_builder_task_intent/v1\nsafety:\n  preview_only: false\n  use_fake_hardware: true\n  allow_simulated_motion: true\n  allow_moveit_execution: true\n  allow_rviz_motion: true\n  allow_real_hardware_motion: false\n  real_robot_locked: true\n",
    r);
  write_file(scene_dir / "urdf" / "scene.urdf.xacro", generated_scene_xacro(scene_dir.filename().string(), resolved_robot_model, resolved_tool_model), r);
  std::string launch = generated_demo_launch();
  const std::string scene_pkg_placeholder = "scene_name";
  const std::string scene_pkg = scene_dir.filename().string();
  const auto pos = launch.find(scene_pkg_placeholder);
  if (pos != std::string::npos) launch.replace(pos, scene_pkg_placeholder.size(), scene_pkg);
  write_file(scene_dir / "launch" / "demo.launch.py", launch, r);
  write_file(scene_dir / "launch" / "demo.rviz", "Panels:\n  - Class: rviz_common/Displays\n", r);
  const auto contains_any = [](const std::string & value, const std::vector<std::string> & needles) {
    return std::any_of(needles.begin(), needles.end(), [&](const std::string & needle) { return value.find(needle) != std::string::npos; });
  };
  const bool robot_package_resolved = contains_any(request.robot_id, {"ur", "fanuc", "abb", "kuka", "motoman", "franka"});
  const bool robot_xacro_resolved = robot_package_resolved;
  const bool ee_requested = request.end_effector_id != "none";
  const bool ee_package_resolved = ee_requested && contains_any(request.end_effector_id, {"robotiq", "suction", "airpick", "gripper"});
  const bool end_effector_xacro_resolved = ee_requested && ee_package_resolved;
  const bool base_link_resolved = robot_xacro_resolved;
  const bool flange_link_resolved = !ee_requested || end_effector_xacro_resolved;

  const std::string robot_visual_mode = robot_xacro_resolved ? "real_xacro" : "placeholder";
  const std::string end_effector_visual_mode = !ee_requested ? "none" : (end_effector_xacro_resolved ? "real_xacro" : "placeholder");
  const bool rviz_truth_preview_ready = robot_xacro_resolved;

  std::vector<std::string> readiness_blockers;
  if (!robot_package_resolved) readiness_blockers.push_back("missing robot package");
  if (!robot_xacro_resolved) readiness_blockers.push_back("missing robot xacro");
  if (ee_requested && !ee_package_resolved) readiness_blockers.push_back("missing ee package");
  if (ee_requested && !end_effector_xacro_resolved) readiness_blockers.push_back("missing ee xacro");
  if (!base_link_resolved) readiness_blockers.push_back("unresolved base link");
  if (ee_requested && !flange_link_resolved) readiness_blockers.push_back("unresolved flange link");

  std::vector<std::string> readiness_warnings;
  if (robot_visual_mode == "placeholder") readiness_warnings.push_back("robot preview uses placeholder visual");
  if (end_effector_visual_mode == "placeholder") readiness_warnings.push_back("end effector preview uses placeholder visual");
  readiness_warnings.push_back("moveit truth preview not wired");

  std::ostringstream readiness_json;
  readiness_json
    << "{\n"
    << "  \"placeholder_launch_only\": false,\n"
    << "  \"rviz_truth_preview_ready\": " << (rviz_truth_preview_ready ? "true" : "false") << ",\n"
    << "  \"moveit_truth_preview_ready\": false,\n"
    << "  \"urdf_xacro_path\": \"urdf/scene.urdf.xacro\",\n"
    << "  \"launch_path\": \"launch/demo.launch.py\",\n"
    << "  \"robot_visual_mode\": \"" << robot_visual_mode << "\",\n"
    << "  \"end_effector_visual_mode\": \"" << end_effector_visual_mode << "\",\n"
    << "  \"robot_xacro_resolved\": " << (robot_xacro_resolved ? "true" : "false") << ",\n"
    << "  \"end_effector_xacro_resolved\": " << (end_effector_xacro_resolved ? "true" : "false") << ",\n"
    << "  \"blockers\": " << to_json_string_array(readiness_blockers) << ",\n"
    << "  \"warnings\": " << to_json_string_array(readiness_warnings) << "\n"
    << "}\n";
  write_file(scene_dir / "generated" / "scene_package_readiness.json", readiness_json.str(), r);
  write_file(scene_dir / "GENERATED_SCENE_SUMMARY.md", "# Generated Scene\n\nNo robot motion commanded.\n", r);
  write_file(scene_dir / "preview" / "static_preview.html", "<html><body><h1>Static Preview</h1><p>No robot motion commanded.</p></body></html>\n", r);
  write_file(scene_dir / "smoke" / "offline_smoke_summary.txt", "status=PASS\nno_robot_motion_commanded=true\n", r);
  write_file(scene_dir / "smoke" / "offline_smoke_report.json", "{\"status\":\"PASS\"}\n", r);
  write_file(scene_dir / "smoke" / "offline_smoke_report.html", "<html><body>PASS</body></html>\n", r);

  r.status = r.blockers.empty() ? (preview_only ? "PREVIEW_ONLY" : "READY") : "BLOCKED";
  r.success = r.blockers.empty();
  if (robot_entry) {
    r.next_commands.push_back(
      "Resolver priority seeded from discovered robot package: " + robot_entry->description_package +
      (robot_entry->urdf_or_xacro.empty() ? std::string("") : (" (xacro hint: " + robot_entry->urdf_or_xacro + ")")));
  } else {
    r.next_commands.push_back(
      "Resolver fallback active for robot selection; next action: map robot id to a discovered catalog entry.");
  }
  if (tool_entry) {
    r.next_commands.push_back(
      "Resolver priority seeded from discovered tool package: " + tool_entry->description_package +
      (tool_entry->urdf_or_xacro.empty() ? std::string("") : (" (xacro hint: " + tool_entry->urdf_or_xacro + ")")));
  } else {
    r.next_commands.push_back(
      "Resolver fallback active for tool selection; next action: map tool id to a discovered catalog entry.");
  }
  r.next_commands.push_back("colcon build --symlink-install --packages-select " + scene_dir.filename().string());
  r.next_commands.push_back("ros2 launch " + scene_dir.filename().string() + " demo.launch.py use_fake_hardware:=true");
  return r;
}

}  // namespace workcell_builder
