# Autogenerated from ROS 1 launch file.
from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, GroupAction
from launch.actions import IncludeLaunchDescription
from launch.conditions import IfCondition, UnlessCondition
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch.substitutions import Command
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node
from launch_ros.actions import PushRosNamespace
from launch_ros.parameter_descriptions import ParameterValue
import os

def generate_launch_description():
    actions = []
    actions.append(DeclareLaunchArgument('db', default_value='false'))
    actions.append(DeclareLaunchArgument('debug', default_value='false'))
    actions.append(DeclareLaunchArgument('limited', default_value='false'))
    actions.append(IncludeLaunchDescription(PythonLaunchDescriptionSource(os.path.join(get_package_share_directory('ur5_moveit_config'), 'launch/planning_context.launch.py')), launch_arguments=dict([('load_robot_description', 'true'), ('limited', LaunchConfiguration('limited'))]).items()))
    actions.append(Node(package='joint_state_publisher', executable='joint_state_publisher', name='joint_state_publisher', parameters=[{'/use_gui': 'false'}, {'/source_list': '[/move_group/fake_controller_joint_states]'}]))
    actions.append(Node(package='robot_state_publisher', executable='robot_state_publisher', name='robot_state_publisher', output='screen', respawn=True))
    actions.append(IncludeLaunchDescription(PythonLaunchDescriptionSource(os.path.join(get_package_share_directory('ur5_moveit_config'), 'launch/move_group.launch.py')), launch_arguments=dict([('allow_trajectory_execution', 'true'), ('fake_execution', 'true'), ('info', 'true'), ('debug', LaunchConfiguration('debug'))]).items()))
    actions.append(IncludeLaunchDescription(PythonLaunchDescriptionSource(os.path.join(get_package_share_directory('ur5_moveit_config'), 'launch/moveit_rviz.launch.py')), launch_arguments=dict([('config', 'true'), ('debug', LaunchConfiguration('debug'))]).items()))
    actions.append(IncludeLaunchDescription(PythonLaunchDescriptionSource(os.path.join(get_package_share_directory('ur5_moveit_config'), 'launch/default_warehouse_db.launch.py')), condition=IfCondition(LaunchConfiguration('db'))))
    return LaunchDescription(actions)
