# Autogenerated from ROS 1 launch file.
from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, GroupAction
from launch.actions import IncludeLaunchDescription
from launch.conditions import IfCondition, UnlessCondition
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch.substitutions import Command
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node
from launch_ros.actions import PushRosNamespace
from launch_ros.parameter_descriptions import ParameterValue
import os

def generate_launch_description():
    actions = []
    actions.append(DeclareLaunchArgument('pipeline', default_value='ompl'))
    actions.append(IncludeLaunchDescription(PythonLaunchDescriptionSource(os.path.join(get_package_share_directory('ur5_moveit_config'), 'launch/' + LaunchConfiguration('pipeline') + '_planning_pipeline.launch.py'))))
    return LaunchDescription(actions)
