# Generated by Easy Manipulator Improved ROS 2 conversion.


from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument
from launch.conditions import IfCondition, UnlessCondition
from launch.substitutions import LaunchConfiguration, PathJoinSubstitution
from launch_ros.actions import Node
from launch_ros.substitutions import FindPackageShare
from moveit_configs_utils import MoveItConfigsBuilder


PACKAGE_NAME = "ur5_moveit_config"
ROBOT_NAME = "ur5"
DESCRIPTION_PACKAGE = "ur_description"
URDF_PATH = ['urdf', 'ur.urdf.xacro']
SRDF_PATH = ['config', 'ur5.srdf']
URDF_MAPPINGS = {'ur_type': 'ur5'}


def build_moveit_config():
    return (
        MoveItConfigsBuilder(ROBOT_NAME, package_name=PACKAGE_NAME)
        .robot_description(
            file_path=PathJoinSubstitution([FindPackageShare(DESCRIPTION_PACKAGE), *URDF_PATH]),
            mappings=URDF_MAPPINGS,
        )
        .robot_description_semantic(
            file_path=PathJoinSubstitution([FindPackageShare(PACKAGE_NAME), *SRDF_PATH])
        )
        .robot_description_kinematics(
            file_path=PathJoinSubstitution([FindPackageShare(PACKAGE_NAME), "config", "kinematics.yaml"])
        )
        .robot_description_planning(
            file_path=PathJoinSubstitution([FindPackageShare(PACKAGE_NAME), "config", "joint_limits.yaml"])
        )
        .to_moveit_configs()
    )


def generate_launch_description():
    moveit_config = build_moveit_config()

    robot_state_publisher = Node(
        package="robot_state_publisher",
        executable="robot_state_publisher",
        output="screen",
        parameters=[
            moveit_config.robot_description,
            moveit_config.robot_description_semantic,
            moveit_config.robot_description_kinematics,
            moveit_config.robot_description_planning,
        ],
    )

    return LaunchDescription([robot_state_publisher])
